### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by skarsgal** [FrankBijnen/ExifToolGui#144]
I have tested last v6.20 x64 and I have see that program save its setting inside file **ExifToolGuiV6.ini**, but this file is always saved in the (sub)folder: **C:\Users\User_name\AppData\Roaming\ExifToolGui**.
In this way the program is not fully portable because it write its settings in the Windows system.
So I ask You that the program save the file  ExifToolGuiV6.ini near the executable program.
Thanks beforeha

**Comment by FrankBijnen** [comment]
You can prevent writing the INI file by adding a commandline parameter: /DontSaveIni
If you save the ini file near the program, it wiil be read, but not saved.

See also: https://github.com/FrankBijnen/ExifToolGui/issues/65
