### ISSUE TITLE
Notice for missing WebView2Loader.dll

### ISSUE THREAD

**Issue by Nzara** [FrankBijnen/ExifToolGui#167]
As long as WebView2Loader.dll is not installed correctly, OSM Map will not work. Unfortunately, this is probably not obvious to most users. They rather suspect a defect in the app. 

The app should check the installation of WebView2Loader.dll. If the map cannot be displayed, a respective notice should be displayed instead of the map.

Of course, it would be even more convenient if the app would install the DLL automatically.

**Comment by FrankBijnen** [comment]
Will look into it

**Comment by FrankBijnen** [comment]
I have added this notice in case the DLL can not be loaded, AND internet access is enabled in Preferences.

![WebView2Loader_dll](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e1885991-1010-406f-aab0-14bbea9c0deb)

'The WebView2Loader.dll could not be loaded.' 'Show Online help?'
If you click Yes this URL is opened: 
https://github.com/FrankBijnen/ExifToolGui/blob/Development/Docs/ExifToolGUI_V652.md#m_edge

Notes:
- Automatic Download and Install would be nice, but I'm also considering to create an installer that handles all prerequisites.
- I'm also updating the documentation (issue 164), once I have completed that, I will create a new release containing this fix.
- The final Url will be changed when I release a new version to https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V652.md#m_edge

Hoping you can agree with these changes, I will close the issue.
