### ISSUE TITLE
Add a peek/preview for strings in right panel

### ISSUE THREAD

**Issue by wsyxbcl** [FrankBijnen/ExifToolGui#181]
It would be helpful when there are long strings (e.g. a taglist) in metadata. A preview will show more info without resizing the panel and also improve the readability.

**Comment by FrankBijnen** [comment]
I have fixed this issue by adding a 'hint'. The hint will popup when you hover over the line.
It will be in a next release, dont know yet when that will be. Or you can build the source yourself.

Frank
P.S. You can use the 'Log Window'  to create a list of the tag(s) you are looking for.
- Open the Log Window
- Type in ExifTool Direct '-r -ext xxx -tagname' + Enter
- Copy the output to the clipboard and paste in your favourite editor.

![hint](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/8b7d9058-9d93-4744-841a-0f69e043b9ad)
![logwindow](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/fa998a26-c721-4766-888f-7ff7b1cd7513)
