### ISSUE TITLE
bug when installing Version V6.2.6 ExifToolGUI_X64.exe on Win11

### ISSUE THREAD

**Issue by tricoffee** [FrankBijnen/ExifToolGui#188]
ERROR:ExifTool not found!
To resolve this you can:
-Install Exiftool in:C:\MyTools\
-Install Exiftool in a directory in the Windows search sequence.
For example in a directory specified in the PATH environment variable.For more info see the documentation on the CreateProcess function.-Locate Exiftool.exe and specify the location in Preferences/Other.
For info on obtaining Exiftool,follow the link in the About box to Github.
Metadata operations disabled.

**Comment by tricoffee** [comment]
Download the executable file exiftool (- k). exe of ExifTool(https://exiftool.org/index.html), place it in the same directory as ExifToolGUI.exe, and rename it exiftoole.exe. In this way, the ExifToolGUI can automatically recognize ExifTools
Refer to Requirements and preparations from this website https://exiftool.org/gui/

**Comment by FrankBijnen** [comment]
https://exiftool.org/gui refers to V5 documentation.
The updated documentation for V6 can be found here: https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md or if you prefer HTML markup: https://htmlpreview.github.io/?https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md
