### ISSUE TITLE
Preview cuts off part of images

### ISSUE THREAD

**Issue by CodeMarc11** [FrankBijnen/ExifToolGui#203]
The preview window can cut off part of an image, depending on the aspect ratio of the image and preview window.

Here is an example cutting off vertically. I intentionally made the preview area wide to make the bug more apparent:
![Preview cut off](https://github.com/FrankBijnen/ExifToolGui/assets/38742926/25a02dfe-01e7-4e38-8014-0276a76abb4c)

This is the actual image:
![Preview - actual image](https://github.com/FrankBijnen/ExifToolGui/assets/38742926/e4479f14-0b0d-4c1c-8e08-fb017103321c)

A similar thing happens horizontally (again, making the preview area narrow to show it more clearly). Preview vs actual image:
![Preview2 cut off](https://github.com/FrankBijnen/ExifToolGui/assets/38742926/c22bd330-ee82-432f-a9e3-8835fcdc7842)
![Preview2 - actual image](https://github.com/FrankBijnen/ExifToolGui/assets/38742926/df12d0e3-78be-462a-9ef8-db3946d001ca)

This is on Windows 11, with the x64 v6.2.6 build. Current exiftool v12.7.0 and current WebView2Loader.dll v1.0.2210.55. I have Windows display scaling at 150% (on the off chance that matters).

**Comment by FrankBijnen** [comment]
Hello 'CodeMarc11',

I have just made a fix for this issue. It is still in the Development branch. I'm planning to release V6.2.7 shortly. This fix will be included.

**Comment by FrankBijnen** [comment]
@CodeMarc11 Did you manage to confirm that this bug is also fixed in the PreRel?

**Comment by CodeMarc11** [comment]
Just checked, yes, both are fixed. Also noticed that Preview resizes and adds padding when the Preview area is resized now, without needing to switch images. 👍

**Comment by FrankBijnen** [comment]
Thnx again
