### ISSUE TITLE
Copy GPS info only when copying metadata?

### ISSUE THREAD

**Issue by colemar** [FrankBijnen/ExifToolGui#214]
![ImportExifGpsOnly](https://github.com/FrankBijnen/ExifToolGui/assets/3066000/f9f3ce49-853a-49c0-b7ea-d885ff8f4bfa)

It seems impossible to copy GPS info only, that is **do not** overwrite other exif tags like CreateDate.

**Comment by FrankBijnen** [comment]
Is this what you propose?

![gps_all](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/d4766fb2-c3fe-4ee7-9d71-598d151972e4)

And the generated command: -tagsfromfile <input> -Gps:all <outputfiles>

**Comment by colemar** [comment]
Exactly! Thank you.

Even better: -tagsfromfile [inputfile] -Gps:all [outputfiles] -wm cg
so that existing tags are not changed.

Even though I just realized it can be (almost) done using the map functions.

**Comment by FrankBijnen** [comment]
-You're welcome. I can add this to a new release. Could take another month. It's not urgent?

A few remarks:
- "-wm cg" I could add that, but it would be clearer if that was a checkbox selectable by the user, and it would apply to all options. Not just Gps. Should I add it?
- There is another dialog that has simular options. It shows when you select 'Copy metadata into (all) JPG or TIF files...'. That doesn't need changing in my view. Agree?

Alternatives:
- You already mentioned the 'OSM Map' . I think that works better. You can see what you're doing, you dont need to have a source file with GPS data, and you have the option to setup 'location data' (Country/Province/City)
One drawback: It only updates the Latitude(ref) and Longitude(ref). Altitude for example is untouched.
- You could add a predefined command to ET direct, like the example. First select all files to update, choose the predefined command, replace &lt;sourcefile&gt; with the name of your source and press Enter.

P.S.: I appreciate your feedback. 

![copy_2](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/4b443bcd-3aff-4e6b-92e0-d675dc15f743)
![menu_copy](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/8091db35-556b-48a8-a1bb-c64692942f7d)
![etdirect](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/2051d29f-8d07-441e-afd3-3166c76fd8f3)

**Comment by colemar** [comment]
> -You're welcome. I can add this to a new release. Could take another month. It's not urgent?

Please take your time, it is not urgent.

> * "-wm cg" I could add that, but it would be clearer if that was a checkbox selectable by the user, and it would apply to all options. Not just Gps. Should I add it?

Yes, this makes more sense.

> * There is another dialog that has simular options. It shows when you select 'Copy metadata into (all) JPG or TIF files...'. That doesn't need changing in my view. Agree?

Agreed.

> * You could add a predefined command to ET direct, like the example. First select all files to update, choose the predefined command, replace <sourcefile> with the name of your source and press Enter.

I see it now, I am new to ExifToolGUI.
It would be spectacular if \<sourcefile\> were a special expression that triggered a file selection dialog.

**Comment by FrankBijnen** [comment]
Thanks. I will add the checkbox.

The 'special expression' that triggers a file selection dialog I will postpone.

**Comment by FrankBijnen** [comment]
Added the option -wm cg.
This is how it looks now. Will be available in a next release.

Thanks for your feedback,
Frank
![copymetadata](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/d5215f80-7289-4868-b81b-663a4af9a178)
