### ISSUE TITLE
Camera settings display in Filelist

### ISSUE THREAD

**Issue by robshea** [FrankBijnen/ExifToolGui#215]
In the Filelist panel, when I select the Camera settings option, none of the camera settings are displayed in the table. They do appear in the Metadata panel. Do you know if there is anything I need to do to get the camera information to appear here?

![Screenshot 2023-12-26 at 12 23 17 PM](https://github.com/FrankBijnen/ExifToolGui/assets/309041/dd703fe0-bafd-4e75-8dba-4414507b14cb)

**Comment by FrankBijnen** [comment]
The data in the filelist is handled by ExifToolGUI directly, in the metadatalist by ExifTool. I guess the filetype RAF can not be handled by ExiftoolGUI.

If you post a sample I will have a look. No promises...

**Comment by robshea** [comment]
Here is a [sample RAF file](https://www.dropbox.com/scl/fi/fw49al3ifsycklj1eho3j/2020-09-26_DSF8981.raf?rlkey=q8j18ocztkjbjlh8p38p6x7cd&dl=1). Thanks!

**Comment by FrankBijnen** [comment]
Thanks.
Give me some time, and dont get your hopes up high.

An alternative would be to add your fields to the user defined view. It will be much slower, but no doubt it will work.

Frank

**Comment by robshea** [comment]
Adding the fields I need to the **User defined** view works great! This lets me quickly see which images I have not yet applied lens data when shooting with multiple lenses. Thank you so much for all of your work on this!

![Screenshot 2023-12-27 at 9 56 44 AM](https://github.com/FrankBijnen/ExifToolGui/assets/309041/77061178-65c4-47f9-ae74-653700848903)

**Comment by FrankBijnen** [comment]
Thanks for your feedback!

Meanwhile I made some progress on the camera settings in the filelist.

![rafmetadata](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/f823b368-5ef7-4a54-a47e-b6eb15101e4e)

Would you like to test it? If yes, I could send you the update exe, via Wetransfer.

Frank

**Comment by robshea** [comment]
I would be happy to test!

**Comment by FrankBijnen** [comment]
Wasn't that difficult. Just have to skip a Fuji header. Found this layout:

(*
Fuji Raw File (RAF)

RAF File Header

0x00    16    'FUJIFILMCCD-RAW ' Magic word
0x10    4     '020x' Format version
              0200: Fuji S2
              0201: Fuji S3
0x14    8     Camera number ID
0x1C    32    Camera body name

RAF File subHeader (01.00)

0x00    4     '0100' Version
0x04    5*4   Unknown
0x18    4     Jpeg Image data offset <== This is the pointer we need. Marked in the screenshot
0x1C    4     Jpeg Image data byte size
0x20    4     First RAW image header offset
0x24    4     First RAW image header byte size;
0x28    4     First RAW image data offset
0x2c    4     First RAW image data byte size
0x30    3*4   Unknown
0x3c    4     Second RAW image header offset
0x40    4     Second RAW image header byte size;
0x44    4     Second RAW image data offset
0x48    4     Second RAW image data byte size
0x4c    3*4   Unknown
*)

![htmldump](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/175cb925-e07e-4d5c-b4f7-2d4d595272e7)

Will send the executable to your mailaddress on dbtlabs

**Comment by robshea** [comment]
That worked! I've checked RAF images from a variety of Fujifilm cameras and they display the camera settings. Thanks!

**Comment by FrankBijnen** [comment]
Thanks for your feedback.

Meanwhile I had to release a hotfix, because of Geoode issues. And that version includes this update.

Frank
