### ISSUE TITLE
ini file in same directory instead of appdata?

### ISSUE THREAD

**Issue by willygeerts** [FrankBijnen/ExifToolGui#224]
The ini file for ExifToolGUI_X64.exe is created in the user's appdata.
Is it possible to have it in the same directory as ExifToolGUI_X64.exe? Making the tool fully portable if one want to.

**Comment by FrankBijnen** [comment]
Hello Willy,

Please read: https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/Readme%20Portable.txt
It explains why it was changed, and how you can prevent from writing to appdata. (/DontSaveIni)

Frank
