### ISSUE TITLE
Windows Defender finds Trojan

### ISSUE THREAD

**Issue by ErikKrause** [FrankBijnen/ExifToolGui#235]
Windows Defender finds Trojan:Win32/Bearfoos.A!ml in ExifToolGUI_X64.exe. Virustotal says "2 security vendors and no sandboxes flagged this file as malicious". Windows Defender finds nothing in the 32 bit version.

**Comment by FrankBijnen** [comment]
Sorry cant reproduce. Will close the issue.

This is what I have done:

- Ran a full scan on my Dev machine.
- Downloaded  the  exe again from the release.
- Checked with Windows Defender: OK
- Checked with Trendmicro Housecall: OK
- Checked with ESET: OK
- Checked with Virustotal: Only 1 <b>ONE</b> vendor out of <b>72</b> reported this file as malicious. Very likely that it's a false positive. 

My opinion:
- If you search for the virus name you can find that it is 'Machine Learned' (the name ends with <b>!ml</b>) They are known to trigger false positives.
- Have a look at the download statistics: https://hanadigital.github.io/grev/?user=FrankBijnen&repo=ExifToolGui With over 1000 downloads for this release, it's highly unlikely that it would be infected without more people noticing.
- If you're still not convinced. Build the exe yourself from source, After all GitHub is for source-code, the release is only there for convenience.

Full scan Devbox:
![devbox](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/b6fd11c3-6659-4c7b-8fc8-a0961f672db7)

Defender:
![defender](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e58dce13-c677-4bc9-a18a-3a2de3a9f6f0)

Houscall:
![housecall](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/c5122f78-ce0f-4eff-9bed-1d049603a5de)

Eset:
![eset](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/6792d191-12dc-43d4-b620-512737c7663c)

VirusTotal:
![virtustotal](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/3d335bcc-a3ac-488a-bd48-95b5e5b331a2)

**Comment by ErikKrause** [comment]
I know that this is likely a false positive. I only wanted to let you know. As a sidenote: Microsoft Defender SmartScreen considers EXIFToolGui an unknown app and tries to prevent starting.

**Comment by FrankBijnen** [comment]
Thanks for letting me know. I do take it seriously, as you may have noticed.
I'm aware of the 'Microsoft Defender SmartScreen' warnings.
