### ISSUE TITLE
Feature Request: Add keyboard shortcuts

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#245]
1. when working in the workspace tab, one can already use ↑, ↓, ↵ Enter and Esc for navigation and editing single tags. For saving all edits of the selected file(s) it would be convenient to use the shortcut Ctrl+S instead of clicking on the button "save".
2. when working in the workspace tab it would be convenient to select 
    - the next file of the filelist with the shortcut Ctrl+N
    - the previous file of the filelist with the shortcut Ctrl+Shift+N

**Comment by FrankBijnen** [comment]
Good suggestion.

I would like different shortcuts for navigating to the next/previous file. Ctrl+N is usually a NEW file.
Ctrl + Up/Ctrl + Down?

**Comment by AngusPhoe** [comment]
I agree, Ctrl + ↑, / Ctrl + ↓ is a better solution fpr navigating to the next file. (In my original post I thought of the key bindings of the program mp3tag)

**Comment by FrankBijnen** [comment]
Closed the wrong issue

**Comment by FrankBijnen** [comment]
Closed the issue. Code has been changed. Will be in a next release.

Frank

**Comment by AngusPhoe** [comment]
Thanks!

**Comment by FrankBijnen** [comment]
You're Welcome.

If you would like to test it before the release, I could send you a pre-release via WeTransfer. Will need your Email address for that

Frank

**Comment by AngusPhoe** [comment]
I think, it will also work perfectly without me testing ;-)

Kind regards,

Angus

**Comment by AngusPhoe** [comment]
Having worked a lot today with the tool, questions came up with regard to the feature "jumping to the next/previous file" with Ctrl + ↑, / Ctrl + ↓
1. Let's assume, one edits the value of a tag TAG1 in the workspace. The input has not been confirmed by entering ENTER, yet. 
   * If now Ctrl + ↓ is pressed, what happens with the previously written input? (I assume it is not saved) 
   * After having jumped to the next file, is the same tag TAG1 selected in the workspace? (would make sense for me)
   * Is the tag in the editing mode like in the previous file (or only selected)?
2. Let's assume, one edits the value of a tag TAG1 and confirms the input by entering ENTER. (not pressing the SAVE button). The selection jumps to the next tag TAG2.
   * If now Ctrl + ↓ is pressed, what happens with the previously written input in TAG1? (I would find it intuitive if it is saved) 
   * After having jumped to the next file, is the tag TAG2 selected? (would make sense for me)
   * Is the tag TAG2 only selected like in the previous file (or in the editing mode)?
3. What is the result if more than one file are selected and then Ctrl + ↓ is pressed?

**Comment by FrankBijnen** [comment]
Let's assume, one edits the value of a tag TAG1 in the workspace. The input has not been confirmed by entering ENTER, yet.
        If now Ctrl + ↓ is pressed, what happens with the previously written input? (I assume it is not saved)

**Correct**

        After having jumped to the next file, is the same tag TAG1 selected in the workspace? (would make sense for me)

**Correct**

        Is the tag in the editing mode like in the previous file (or only selected)?

**Only selected**

    Let's assume, one edits the value of a tag TAG1 and confirms the input by entering ENTER. (not pressing the SAVE button). The selection jumps to the next tag TAG2.
        If now Ctrl + ↓ is pressed, what happens with the previously written input in TAG1? (I would find it intuitive if it is saved)

**Not Saved** (Only Save button saves!)

        After having jumped to the next file, is the tag TAG2 selected? (would make sense for me)
        Is the tag TAG2 only selected like in the previous file (or in the editing mode)?

**Tag 2 is only selected**

    What is the result if more than one file are selected and then Ctrl + ↓ is pressed?

**Only the previous/next file is selected, others are unselected**

I would be happy to send you a prerel, so you can test yourself.

Frank

**Comment by AngusPhoe** [comment]
> ```
>     Is the tag in the editing mode like in the previous file (or only selected)?
> ```
> 
> **Only selected**

okay

> ```
> Let's assume, one edits the value of a tag TAG1 and confirms the input by entering ENTER. (not pressing the SAVE button). The selection jumps to the next tag TAG2.
>     If now Ctrl + ↓ is pressed, what happens with the previously written input in TAG1? (I would find it intuitive if it is saved)
> ```
> 
> **Not Saved** (Only Save button saves!)

I understand. One has to remember to first press CTRL+S before pressing CTRL+↓ when saving is intended.
An option would be to add a reminder pop up "There are unsaved changes. Do you really want to continue?". But I find that would only slow up the workflow.
  
> ```
> What is the result if more than one file are selected and then Ctrl + ↓ is pressed?
> ```
> 
> **Only the previous/next file is selected, others are unselected**

Makes sense.
 
> I would be happy to send you a prerel, so you can test yourself.

Gladly but I have never done that before. Shall I send you my email adress?

Kind regards,
Angus

**Comment by FrankBijnen** [comment]
I could send it via wetransfer.

If you add your email address as a comment here I will pick it up. As soon as I have it, I will notify you, so you can delete the post if you want.

**Comment by FrankBijnen** [comment]
I shared a file on my onedrive. Here is the link:
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

I think thats easier.

**Comment by AngusPhoe** [comment]
Thanks for the prelease. I tested the following test cases:
- renaming of files with F2.
  - 👍 
- navigating with CTRL+↑ / Ctrl + ↓ 
  - 👍 works like a charm
- saving changes with CTRL+S 
  - 🤔 After saving, the selection in the workspace jumps back to the first tag. This behaviour has never bothered me because I had to use the mouse anyway. Now, with the functionality of both CTRL+S and CTRL+↑ this behaviour feels awkward - mainly if you want to edit one and the same tag for subsequent selected files. I have attached a screencast to try to demonstrate this usecase.
  - I personally would prefer that the selected tag remains selected after saving. What do you think?

https://github.com/FrankBijnen/ExifToolGui/assets/156246645/a2762526-b349-4df4-b873-86f58006c270

**Comment by FrankBijnen** [comment]
>       * I personally would prefer that the selected tag remains selected after saving. What do you think?

Agree. I had noticed it also. Will look into it.

Maybe I will ask you to test some more, regarding ESC and ENTER. You can have a second look at this.
https://github.com/FrankBijnen/ExifToolGui/issues/261
