### ISSUE TITLE
Load Files also from subfolders

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#246]
In the filelist section there could be a select button "include subfolders" with the according functionality

**Comment by FrankBijnen** [comment]
That would be hard to implement.

You can use subfolders in Exiftool Direct using '-r -ext xxx'. For my personal use that's enough.
Can you give an example what you would like to accomplish?

**Comment by AngusPhoe** [comment]
I sort all my photos and videos in folders in a chronological structure:
* YYYY
  * YYYY-MM-DD event
  * YYYY-MM-DD event
  * ....
* YYYY
  * ....

The photos and videos are from different sources (from my family). I add to every file a value for the XMP-dc:Creator tag based on the model/make information I read from my user defined file list. Furthermore I use some exiftool direct commands to e.g. synchronize date/time information.

Today I do these workflow steps for every folder separately. Works fine. However, I imagine that a mass editing over all folders would speed up the whole process.

No worries, if you don't implement this if it is to complex to accomplish.

**Comment by FrankBijnen** [comment]
OK. Thanks for your clarification.

I dont know what you mean exactly with a 'user defined list' and how that affects the ExifTool command. But setting XMP-dc:Creator while recursing directories can be done with this command. (Assuming you have JPG's)

-XMP-dc:Creator=FrankB -r -ext jpg

-r for recurse dirs
-ext jpg only process jpg. You can specify that more than once.

If you open the log window, before you execute the command you can see the output.

See screesnhots:

![Before](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/6828d53d-2b69-43c0-9de9-a4bea9494554)


![After](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/3826ac1a-804e-42b0-baa3-de9dfea383de)

**Comment by AngusPhoe** [comment]
Thanks for the hints.

In my case, i don't want to tag ALL files within in ONE directory, but SELECTED files within SEVERAL directories. I add a screencast demonstrating this in the programm geosetter. (exiftoolgui is still superior in mass editing than geosetter IMO)

https://github.com/FrankBijnen/ExifToolGui/assets/156246645/8c6cc41c-65f5-4578-a92d-cca7cff8aa38

**Comment by FrankBijnen** [comment]
The only thing I can think of is a combination of -r -ext xxx and -if 

For example:

-r -ext jpg -ext pef -ext dng -gps:all -if "$model eq 'PENTAX K-x'"

This will show '-gps:all' output for jpg, pef and dng file that have model PENTAX K-x

But I agree that it is probably to complex, and not flexible enough. Sorry.
Frank

**Comment by AngusPhoe** [comment]
No worries. I help myself with workarounds ;-). Do you close the issue?

**Comment by FrankBijnen** [comment]
Just did.

Thanks for the suggestion. I like these suggestions. Helps me to understand how people use ExifToolGui.

Frank
