### ISSUE TITLE
Win 11 Pro: The font is unreadably small on a notebook with a 4k screen...

### ISSUE THREAD

**Issue by JensSteyer** [FrankBijnen/ExifToolGui#250]
Hello Frank,

Many thanks for your effort. I thought there would never be another update for this useful tool. ;)

On my notebook with a 4K screen, the font is unreadably small, so unfortunately you can't work with it. (I use Windows 11 Pro on the desktop with 225% scaling. Unfortunately, the current PTGUI update does not recognize this either. Maybe there is a way to adjust that.

Thank you in advance, Jens

![Zwischenablage01](https://github.com/FrankBijnen/ExifToolGui/assets/156354865/554148d2-4b66-410d-bdd7-8eb881a4e17d)

**Comment by FrankBijnen** [comment]
You could try to add:
/HighDpi=PerMonitorAwareV2 /Scale
as command line parameters in the shortcut.

The next version will have this as default. I have had reports from other users that that works fine.
If you're interested I could send you a prerel via WeTransfer, I will need your Email address.

Frank

**Comment by renschmid** [comment]
I can confirm that the text is unreadable on my Surface Pro 7 +. I added the command line as a shortcut and it works fine. Thank you for your efforts.

**Comment by FrankBijnen** [comment]
@renschmid  Thanks for reporting back.

In the next version 6.2.9 the commandline parameters are no longer needed. Also the scaling of the 'File menu' will be better.

@JensSteyer Can you also confirm? If you do, I will close the issue.

**Comment by renschmid** [comment]
Ok thanks

**Comment by capricorn8** [comment]
Great!!! This thread answers my question regarding a readable font also on QVGA displays for the elderly and provides a very welcome emergency aid 😄

Apart from this - Frank, I agree with my Flickr friend @JensSteyer. I'm super happy that you have revived this invaluable tool. Please don't let it down again 😊

**Comment by FrankBijnen** [comment]
> Great!!! This thread answers my question regarding a readable font also on QVGA displays for the elderly and provides a very welcome emergency aid 😄
> 
> Apart from this - Frank, I agree with my Flickr friend @JensSteyer. I'm super happy that you have revived this invaluable tool. Please don't let it down again 😊

You're Welcome
