### ISSUE TITLE
Screen Resolution very high

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#256]
Hello Frank,

I am not sure, but I believe that the new ExifToolGui does not respect the screen "scaling" defined in windows settings. I added a screenshot with a comparison with the Bogdan version to demonstrate this. (I have a screen with a resolution of 2560x1600 and a scaling of 125 % definied in the windows settings)

![resolution_comparison](https://github.com/FrankBijnen/ExifToolGui/assets/156246645/48d7abe7-7b8f-4704-8ea2-d99592daa5b6)

**Comment by AngusPhoe** [comment]
Sorry, only saw now that you mentioned the "/HighDpi=UnAware /Scale" parameter. I close the issue.

**Comment by FrankBijnen** [comment]
Hello Angus,

The 'Prerel 6.2.9' that you downloaded recently does not require these commandline parameters anymore.
You could add /NoScale if you dont want scaling. 

Frank
(Reviewing the issues to update the docs for the new release)
