### ISSUE TITLE
The OSM Map is in Russian?

### ISSUE THREAD

**Issue by renschmid** [FrankBijnen/ExifToolGui#257]
It appears that the OSM Map is in Russian. Is there a setting to default to English?

**Comment by FrankBijnen** [comment]
Good question.

I assume, hope, that the OSM map only displays Russian, when you're looking at Russia? Suppose  you move to Greece, it wil show Greek?

The Openlayers that ExifToolGui uses currently is in the official local language. There is no setting to change that. I did a quick search and the suggestion was done to change to a different tile server. 
https://stackoverflow.com/questions/57067589/how-to-change-openlayers-5-3s-tile-language

I will look into the options. Be patient

Frank

**Comment by renschmid** [comment]
Thanks, Frank. It defaulted to Russian. I was putting in GPS coordinates, not the actual place, because the input box already had pre-filled coordinates. I thought they would resolve. When I went to an Australian or USA location, the maps were in English. Sorry, it was my confusion.

**Comment by FrankBijnen** [comment]
Thanks for your feedback. I will keep this issue open for now. That will remind me to look into the option to have different map layers.

Frank

**Comment by FrankBijnen** [comment]
I had a quick look at other tileservers. But the ones I found were paid. You would need an apikey.
I like to keep ExifToolGui free, so that's not an option.
