### ISSUE TITLE
Feature Request: Shortcut for renaming of file names

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#260]
Hello Frank,

Is it possible to bring back the very valuable feature of renaming a file name with the help of the short cut "F2"?

Kind regards,

Angus

**Comment by FrankBijnen** [comment]
Good point. I'm looking into it. If its a quick fix I'll combine it with the prerel that I will send you

**Comment by FrankBijnen** [comment]
Was a quick fix.
