### ISSUE TITLE
Feature request: add ENTER and ESC functionality in several menu

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#261]
Hello Frank,

As a keyboard guy I like to use the mouse as seldom as possible. 

In some menu a dialog window opens that can be closed by pressing the _key_ ESC or the according action can be confirmed by pressing the _key_ ENTER (e.g. Various -> File: Date modified as in Exif). Fine.
Some other menu open a dialog, where _buttons_ "Cancel" and "Execute" exist but cannot be shortcutted by pressing the _keys_ ESC or ENTER, respectively. (e.g. Modify -> Exif: DateTime shift)

Is that on purpose? Or can that be changed?

**Comment by FrankBijnen** [comment]
Is that on purpose? Or can that be changed?

it's not on purpose. It was already like that in Version 516 by Bogdan. I must admit that I dont like it either.
Will look into it and update where possible. 

Low prio as far as i'm concerned

**Comment by AngusPhoe** [comment]
I agree, low prio

**Comment by FrankBijnen** [comment]
I have just uploaded an new zip file to my Onedrive. Same link: https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

This version has the CTRL/S fixed (Selected rows remains the same) and the dialogs now respond to ESC and ENTER.

Please have a look. Thans in advance.
Frank

**Comment by FrankBijnen** [comment]
Your're Welcome. Thanks for testing and reporting back. Will close the issue.

I'm aiming to release 6.2.9 next week. If you happen to find something regarding this issue dont hesitate to report it.
Frank
