### ISSUE TITLE
ExifToolGUI hangs for most actions

### ISSUE THREAD

**Issue by PaulCoddington** [FrankBijnen/ExifToolGui#277]
Windows 11 Pro 23H2

ExifToolGUI 6.2.9

Application launches, but hangs whenever any action is attempted.

• Hangs when Preferences menu is selected.
• Hangs when any folder is selected in tree.
• Hangs when a file is drag-n-dropped into application from desktop.

**Comment by FrankBijnen** [comment]
A few questions to help pinpoint.

- Did you succesfully run the previous version 628 and after upgrading to 629 the problems began? 
- Can you run the exiftool.exe program? Open a CMD prompt and type exiftool -ver. It should show this:
![ver](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/646735be-4e89-4c42-9fb4-f02272a01b8c)
If that fails, I recommend installing the Olliver Betz version. https://oliverbetz.de/pages/Artikel/ExifTool-for-Windows

**Comment by FrankBijnen** [comment]
@PaulCoddington 

-Any news?
-Can you run Exiftool standalone?

Frank

**Comment by FrankBijnen** [comment]
@PaulCoddington 

It's been a week I have been waiting for your feedback. Will close the issue, as I think the issue did resolve.
