### ISSUE TITLE
Map Center

### ISSUE THREAD

**Issue by Philshappy** [FrankBijnen/ExifToolGui#335]
It is a bit difficult to position the map accurately in the center. Adding an aid, such as a crosshair or circle in the map center would help.

**Comment by FrankBijnen** [comment]
You can use ctrl + left  mouse click.
That centers, and puts the coordinates in the edit box.

**Comment by FrankBijnen** [comment]
@Philshappy 

Do you accept the answer?

**Comment by Philshappy** [comment]
I would prefer crosshairs but using ctrl+left click works for me.
________________________________

**Comment by FrankBijnen** [comment]
Thnx, I close the issue
