### ISSUE TITLE
Preferences problem

### ISSUE THREAD

**Issue by darwin4ever** [FrankBijnen/ExifToolGui#339]
I have two directories, one with ExifToolGUI v6.2.9.exe and one with ExifToolGUI_X64 v6.2.9.exe

When I change something in the preferences of one version (ex the Exiftool.exe location) it is changed in the other version too.
Seems the preferences are not stored together with the exe's and are shared (not stored uniquely)
If I remember well, in the original version the preferences were stored in a file next to the exe's.

As it is now it is not possible to make a full 32-bit (32-bit ExiftoolGUI + 32-bit Exiftool.exe) and a full 64-bit (64-bit ExiftoolGUI + 64-bit Exiftool.exe) setup.

Two questions 
- where are the preferences stored / located now ?
- could they be made unique for 32-bit and 64-bit ?

**Comment by Philshappy** [comment]
C:\Users\'your user directory'\AppData\Roaming\ExifToolGui

**Comment by darwin4ever** [comment]
> C:\Users\USER\AppData\Roaming\ExifToolGui

Is there no way to change that default location ? Next to the exe as it was in the past ?

I mentioned already the 32/64-bit problem but another issue is that it's not possible to Configure / use it as a Portable app which is  pity.

**Comment by Philshappy** [comment]
I am not sure if you move it. if it is not located in the user director than it makes multiple accounts sharing a single computer difficult.

**Comment by FrankBijnen** [comment]
First of all. The change was made, because the program directory maybe readonly. FYI I am preparing an installer for V6.3.0 and that installs the exe by default in Program Files. Which is not writeable by default.

Using the commandline param /DontSaveIni you can create your setup. 
- Delete, or move, the INI from APPDATA
- Create an INI in the 32 bit directory, and a shortcut with /DontSaveIni. The INI will be read from the program dierctory, but not saved.
- And do the same for the 64 directory.

I am curious why you would want the 32 and the 64 bits version both on your system, and not share the same INI?

**Comment by darwin4ever** [comment]
As I wrote, I found [https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/Readme%20Portable.txt](https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/Readme%20Portable.txt) which explains the steps

But that's not flexible as the whole procedure needs to be redone twice if another preference needs to be changed.

Most of such apps are used from a USB-stick on multiple machines either 32-bit or 64-bit, so not "A system". And yes I know 32-bit can be used on a 64-bit machine, but I choose to use the 64-bit versions if available. And that implies also the 64-bit Exiftool.exe.

Leave it up to user how he/she wants to use and configure. If the user runs into a "readonly" problem, then he'll have to change it's setup. Now limitations are build-in to solve a problem that maybe never happens.

For sure the "write ExifToolGuiV6.ini" will return an error when the write-location (Program-directory) is read-only. That could be the trigger to present a warning and choose another location.

There are so many possibilities to solve the might-be problem without losing flexibility and limiting usage.

**Comment by FrankBijnen** [comment]
> As I wrote, I found https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/Readme%20Portable.txt which explains the steps
> 
> But that's not flexible as the whole procedure needs to be redone twice if another preference needs to be changed.

I think you missed something in my previous  reply. 'And not share the same INI?'
Just put the 32 and 64 Bits exe's in the same directory and they can share the same INI. 

> Leave it up to user how he/she wants to use and configure. If the user runs into a "readonly" problem, then he'll have to change it's setup. Now limitations are build-in to solve a problem that maybe never happens.
> 
> For sure the "write ExifToolGuiV6.ini" will return an error when the write-location (Program-directory) is read-only. That could be the trigger to present a warning and choose another location.
> 

My problem is that it's just bad practice to write into the program's folder. That way you can never use 'Program Files' or an installer. Sure I understand that for an USB stick it will work., 

> There are so many possibilities to solve the might-be problem without losing flexibility and limiting usage.

I just need 1 foolproof option. What do you propose that does not write to 'Program Files' or any protected folder?

**Comment by FrankBijnen** [comment]
@darwin4ever 
Have you thought about a solution? I have. Please tell me what you think.

- Add a commandline parm: /IniPath=<path> Special values %P for Program dir and %W for Working dir.
- If this parm is specified, one of the first things to do, after the INI file is read, but  before the user has a chance to do anything, WRITE the INI to that location.
- If there is an error show a message and halt the program
- If OK continue. But then we know for sure that the INI file can be saved on program exit.
- If the parm is not specified, same behaviour as it is now.

Frank

**Comment by darwin4ever** [comment]
> @darwin4ever Have you thought about a solution? I have. Please tell me what you think.
> 

That would be great !

> * Add a commandline parm: /IniPath= Special values %P for Program dir and %W for Working dir.

I would suggest to allow also a full path (with eventual spaces in it) next to %P and %W

> * If this parm is specified, one of the first things to do, after the INI file is read, but  before the user has a chance to do anything, WRITE the INI to that location.

If  /IniPath is specified
a. if ini-file does not exist at /IniPath : create default
b. if ini-file does exist at /IniPath : read/write ini-file

> * If there is an error show a message and halt the program

If there is an error in a. or b. show a message and halt the program

> * If OK continue. But then we know for sure that the INI file can be saved on program exit.
> * If the parm is not specified, same behaviour as it is now.
> 
> Frank

**Comment by FrankBijnen** [comment]
I can send you a prerel if you like, so you can check it yourself.

**Comment by darwin4ever** [comment]
Yes you can send me the zip-file-version. I'll try it out and keep you updated. Looking forward to it :-)

**Comment by FrankBijnen** [comment]
Just to be sure. Here is the download link.
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

**Comment by darwin4ever** [comment]
Hi Frank,

This is great, really a huge improvement !!! Thank you.
All tests I did, had the expected behaviour.

Tests :

1) /IniPath=F:\TestGUI --> error --> ok because dir not existing
2) created dir +  /IniPath=F:\TestGUI --> ok
3) /IniPath="F:\Test GUI" --> ok
4) /IniPath=%P --> ok
5) NO WorkingDir + /IniPath=%W --> ok, same as %P
6) WorkingDir = F:\Test GUI + /IniPath=%W --> ok

Remarks :

1) ReadOnly Location not tested, but test 1) can considered as such
2) 32-bit and 64-bit keep now their specified ExifTool.exe location
