### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by ps81frt** [FrankBijnen/ExifToolGui#346]
hi, i tried change metadata on multiple file time but how do that ?
no explain in Doc.
ty

**Comment by FrankBijnen** [comment]
I think you mean this:
https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md#modify-menu

First select all the files to modify and then use any of these functions.

I would appreciate if you could describe your question better. Maybe add a screenshot?

**Comment by Philshappy** [comment]
Select metadata for the right side panel (next to OSM Map). Then Select all. Now select your photo files (one or more). You should see metadata. You must create a workspace to be able to update metadata. Select a writeable metadata (not all is writeable) right click and an option to add to workspace shoud appear. Add the metadata to the workspace. continue as needed. Then select workspce. only these metadata is shown. you can now select a metadata, on the bottom of the right panel you can enter a value, then enter return. you must select save for the metadata to be updated to the photo. i hope this helps you get started ss there are so many great features you will find this tool very usefull.

**Comment by ps81frt** [comment]
Xhat i do bad pls ?
![Uploading exif.gif…]()

**Comment by FrankBijnen** [comment]
@ps81frt Si tu veut, ecrit ton question en Francais. Je peux lire francais, mais va reprondre en Anglais!

I think you have an error in your user defined fields. On or more of the user defined fields contain a statement to make a modification.
To be sure. Please remove them all. That should make the metadata panel work again.

![deluserdef](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/82e67f63-e62a-49ee-a242-d6a841495dfe)

If you dont care about your settings, you can also delete or rename the INI file:
%APPDATA%\exiftoolgui\exiftoolguiv6.ini

The safe way to add fields to the filelist details, is from the Metadata panel. Set it to EXIF. Find the column you want, and right click, add tag to filelist details.
![addtouserdef](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/137055a4-5c45-47e5-8de4-2c5a6b4a4a4f)

Bon chance

**Comment by FrankBijnen** [comment]
I was able to reproduce it. See the screenshot.
**Dont use an = character in the field!**
![example](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/3c828d0b-8646-45ba-ab21-823b08a87e1d)

I am thinking of checiking that in the program, to prevent it from happening.

**Comment by ps81frt** [comment]
Ho no,
just want says problème really for date:
exemple if i enter
-Quicktime:CreateDate="2018-24-12 04:30:00"

in outuput property file i have 24/12/2018 ok but time is bad always shift 1 Hour 05:30:00

**Comment by FrankBijnen** [comment]
Hello @ps81frt 

For Quicktime you should try -api QuickTimeUtc

https://exiftool.org/forum/index.php?topic=7874.0

You can add that to the Custom Options
![options](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/1a5360f3-9d02-4818-8120-5e0c7cfcffdf)
![quicktime](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e50ea425-4096-459a-9b60-e605e806dfce)
