### ISSUE TITLE
 Style Dark Filelist Highlighted Color

### ISSUE THREAD

**Issue by Philshappy** [FrankBijnen/ExifToolGui#347]
Would it be possible to change the highlighted color when selecting a file for the darker styles. The light blue highlight does not appear well against the dark/slate background. Also it changes to grey which is even more difficult to see.

**Comment by FrankBijnen** [comment]
I agree. Will look into it, and keep you posted.

**Comment by FrankBijnen** [comment]
@Philshappy 

I did some work on this, and I think it has improved. The color of the highlighted line is now the same as on the Metadata panel. 
Also I have made the selected folder in the Treeview on the left Bold. (I tried changing that background color, but without succes)
'
See the screenshot of style Amakrits.

If you would like to test it yourself, here is a downloadlink to a prerel,.
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Frank

![Amakrits](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/cdec9d7f-7a65-40e4-b3a8-92bf2465d4c1)

**Comment by Philshappy** [comment]
I tried this version and it is much improved! I often was switching between Windows 10 and Windows 10 SlateGrey but now I can just keep it on Amakritz.

________________________________

**Comment by FrankBijnen** [comment]
Thanks for testing and reporting back. I'll close the issue. Will be available in the next release.

What you noticed about the initial, and selected, color has to do with 'Selected and not focused', vs 'Selected and focused'. I will have a short look, 5 min at most.
