### ISSUE TITLE
Ask Bogdan Hrastnik for license selection?

### ISSUE THREAD

**Issue by JohnTHaller** [FrankBijnen/ExifToolGui#348]
Would it be possible to ask Bogdan Hrastnik for their preference on an open source license selection? Since packaging it for PortableApps.com, we've had folks ask about it and I'd like to give them some guidance on whether they're allowed to use it at their company of for their freelance projects. I couldn't locate any contact info for them. Thanks!

**Comment by FrankBijnen** [comment]
> Would it be possible to ask Bogdan Hrastnik for their preference on an open source license selection? 

I dont know how to contact him. So the short answer is: No.

I have added my view on the license at the bottom of the README.MD. In short: I could never find a statement from Bogdan about license, so for me, (I'm only continuing his work), it would be weird to add a license statement.

Frank

**Comment by JohnTHaller** [comment]
Thanks Frank. If anyone does find a way to contact Bogdan Hrastnik, please let us know.

**Comment by FrankBijnen** [comment]
@JohnTHaller 

All of sudden, this license matter started moving. Meanwhile we have a statement from Bogdan Hrastnik, via Phil Harvey.

https://exiftool.org/forum/index.php?topic=4002.0

Will reopen this issue and update things.
Frank

**Comment by FrankBijnen** [comment]
License added to Github

About form and installer will be updated with V631
