### ISSUE TITLE
How do I delete a specific tag from any file again?

### ISSUE THREAD

**Issue by fakkoweb** [FrankBijnen/ExifToolGui#349]
This would be simply the equivalent of `exiftool.exe -TAG=` where TAG is the tag name.

I was very surprised from the GUI tool that I cannot simply select a tag, right click and delete. There is a window to delete an entire set of tags, but no option for removing a specific tag I can select from the right view?

I tried also CANC or BACKSPACE on it and looked in every menu, but nothing.

**Comment by FrankBijnen** [comment]
I agree there is no menu option to do that. But it can be done:

- In the Workspace, select the line with the tag you wish to remove.
- Press Enter to move the focus to the Edit Box, or click on the Edit Box.
- Empty the Edit Box
- Press Enter again.
- Click on Save (Or Ctrl + S)

![clear](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/2f9237b1-7a79-4d2d-bf17-4af8425d6264)

You can check in the Log-Window the command issued:
![log](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/9f72ce1c-c7bd-4e4c-b341-dc5e03994760)

**Comment by fakkoweb** [comment]
It seems I have no edit box at the bottom. I am modifying a pdf. So pressing ENTER after selecting a tag does nothing.
I am on V6.2.9.0 32 bits.

**Comment by FrankBijnen** [comment]
![window](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/c54a05a0-3d80-4bd7-9525-e8b2e06c0288)

- It should show if you click on Workspace
- If not you can try to reset the sizes. 1) Hover with the mouse over the taskbar icon 2) Click on reset size to default
- Still no luck. Send a screenshot
