### ISSUE TITLE
Feature Request - ability to export predefined ExifTool direct commands.

### ISSUE THREAD

**Issue by orichardt** [FrankBijnen/ExifToolGui#351]
As hopefully many, as I, have amassed a lot of predefined ExifTool direct commands, it would highten efficiency to be able to export them into possibly a txt file, with the name and the command.
Another idea could be to be able to re-arrange the order, possibly alphabetically.
Thank you for an excellent continuation and enhancing of a great program!

Ole Richardt Nielsen

**Comment by FrankBijnen** [comment]
@orichardt

First of all thanks for your compliments. Compliments were not the reason to revive the project, but it's always nice to receive them!

About your idea. I really like it. Not only an export, but also an import I assume? I will keep the issue open, and it will be addressed. Dont know when. Because I'm 'finishing' the Version 6.3.0 for weeks now. Each time new ideas keep popping up, that prevent me from releasing it.

You do know that the commands are stored in the INI file: %APPDATA%\ExiftoolGui\ExiftoolGuiV6.ini ? If your concern is to create a backup, it might be enough to copy that file.

Frank

**Comment by orichardt** [comment]
You are welcome, and yes import was also on my mind. It would just help to share commands, import into new/other instances, and make it more friendly. 

Thanks for keeping the request open and I know the hardest thing at new versions is to set a stop for new fixes and features to get the version out 😊

Yes, I’m keeping copies of the INI file as backups.

regards,
Ole

**Comment by FrankBijnen** [comment]
@orichardt

As [Philshappy](https://github.com/Philshappy) mentioned in issue https://github.com/FrankBijnen/ExifToolGui/issues/356
he thought it would be a good idea to be able to also save the 'Filelist user details' columns. I'm adding that to this issue.

Frank

**Comment by FrankBijnen** [comment]
@orichardt 

I have a version ready that can load and save the ExifTool direct commands. And also the user defined fields in the filelist.
The menu items are in the 'program' menu. Should be self-explanatory.

If you want to have a look, here is a link to a prelrel. (I still have to do thorough testing, so please be prepared for bugs!)

https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

**Comment by orichardt** [comment]
Hi Frank, thank you very much for the pre-rel. I’ve tested it and in relation to the load/save for the ExifTool direct commands.

I have not encountered any bugs, I’ve tried to be inventive to the txt file  when updating it in notepad, pls. See screenshot 😊 ( I guess it should not matter as it’s just reading txt file, but I have tried with foreign characters and symbols)

***@***.***

I have a comment, though, when I activate the dropdown, it always default to the last entry so have to scroll up every time. Could it default to the top line instead?

Thank you again,

regards,
Ole

**Comment by FrankBijnen** [comment]
Hi Ole,

Thanks very much for testing. See my remarks.

> Hi Frank, thank you very much for the pre-rel. I’ve tested it and in relation to the load/save for the ExifTool direct commands. I have not encountered any bugs, I’ve tried to be inventive to the txt file when updating it in notepad, pls. See screenshot 😊 ( I guess it should not matter as it’s just reading txt file, but I have tried with foreign characters and symbols) ***@***.***

If you reply directly to the mail, Github discards the attachments. So I dont see the screenshot. If you think I really need to see it, upload it in GitHub.

> I have a comment, though, when I activate the dropdown, it always default to the last entry so have to scroll up every time. Could it default to the top line instead?

If I understand you correctly, then what you want can be done with the button '^Default'.  It is saved in ExifToolGuiV6.ini in section [GUIsettings] ETdirDefCmd=x

![a](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/369eade2-f7dc-434c-b56c-c77d7486e69b)

Meanwhile I have extended the list with some more options:
![b](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/409d4f7b-6609-4cbb-9179-796581480805)

Frank

**Comment by FrankBijnen** [comment]
@orichardt 

Oh yes. Forgot to ask. If you have ET Direct commands that would be useful to add as samples, let me know. I will be happy to add them to the distribution.

Frank

**Comment by orichardt** [comment]
Hi Frank, thank you for the feedback. You are right, the start of the dropdown is controlled by '^Default' so works. 😊

Actually the option of saving the user defined filelist layout was also on my “list”, so that’s perfect.
As these (filelist and workspace) at least in my instance relate (I have one set of layouts for photos and one set for videos (mp4) then a future idea could be to load them together, alike a “theme” or being able to recognize them on the interface as the ini file loaded so at a glance it’s possible to see if your layout “fits”.  I know that this is extending it quite a bit, but just as an idea 😊

Thanks again.

regards,
Ole

**Comment by FrankBijnen** [comment]
@orichardt 

Hi Ole,

Some time ago we had this conversation about exporting/importing GUI settings.

Maybe this issue will also interest you. https://github.com/FrankBijnen/ExifToolGui/issues/418 
With the yet to be released V6.3.5. you can customize the tags to remove and copy. What's more these settings can be saved and restored.

![predefined](https://github.com/user-attachments/assets/0ae873af-8fd2-4b91-b004-7976b41408e4)

If you would like to try it, and maybe give me some advice, here is the download link.
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Frank

**Comment by orichardt** [comment]
Hi Frank, thank you for this - I’ll definitely try it out and come with my comments, and some examples on how I’ve used it!

Ole

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FrankBijnen** [comment]
Hi Ole,

Just to inform you. I have tried to document the changes:

https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V635.md
See 'Managing metadata' and 'Scanning and displaying sub folders in the filelist'

Also updated the pre-rel. Some smaller things were fixed.

Frank
