### ISSUE TITLE
REST request failed: Error sending data: (12175) on “m 'Modify/Update City, Province, Country from GPS coordinates”

### ISSUE THREAD

**Issue by apprenti-sorcier** [FrankBijnen/ExifToolGui#358]
Thank you for reviving the ExifToolGUI.

I’m using the latest ExifTool 12.79 and GUI 6.3.0 (tried on the installer or the portable versions) on Windows 7 Home 64 bits French.

I activated all geocoding from the preferences and I added an API key for geocode.maps.co I used the same key on their website and it works.

However, every time I use the “Modify/Update City, Province, Country from GPS coordinates” function with Geocode or Overpass, I get this error box and the reverse geocoding doesn’t work.
![Image du presse-papiers](https://github.com/FrankBijnen/ExifToolGui/assets/161721020/561973bf-7ff7-4c54-a205-a8490d430d43)

Then the Geolocation window appears, but it has no data. When I select from the drop‐down list country, city… there is a second error:
![Image du presse-papiers (1)](https://github.com/FrankBijnen/ExifToolGui/assets/161721020/47c96755-673b-48fe-858d-43a8af50f648)
[stacktrace.txt](https://github.com/FrankBijnen/ExifToolGui/files/14627420/stacktrace.txt)

This kind of second error also appears if I select first another provider like Overpass or even the ExifTool geolocation feature from the list.

If is relevant in any way, the new ExifTool geolocation feature works well from the command line.

**Comment by FrankBijnen** [comment]
Bonjour. (Je peux lire Francais!)

With Windows 7 it is hard to get this function working. I managed somehow, but I'm not sure what made the difference and I dont recommend it. 
What seemed to make a difference is the 'TLS version' It needs at least  Version 1.2. 

- Google for 'Windows 7 TLS 1.2' and you will find more info.

- Also I'm posting here a registry hack, that I need to make it work. But I cant give guarantees...

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp]
"DefaultSecureProtocols"=dword:00000800

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp\Passport Test]
"ConfigVersion"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp\Tracing]
 
```

As a workaround you can use the Geocode provider 'Exiftool geocode'. That doesn't need Internet, webservices etc.
See the screenshots.
![geocode](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/27607b64-a279-474e-936f-53acd0a7d5cb)
![geocode 2](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/461b6245-f161-43b3-ac0c-21187d08f2c8)

Frank

**Comment by apprenti-sorcier** [comment]
Merci Frank. Ça a fonctionné avec cette modification. Je devrais prendre le temps de mettre à jour mon Windows !

**Comment by FrankBijnen** [comment]
De rien.
Avec quelle modification?

Je vais fermer le 'issue'. D'accord?

**Comment by apprenti-sorcier** [comment]
✓
TLS 1.2 (https://support.microsoft.com/fr-fr/topic/mise-%C3%A0-jour-pour-activer-tls-1-1-et-tls-1-2-en-tant-que-protocoles-s%C3%A9curis%C3%A9s-par-d%C3%A9faut-dans-winhttp-dans-windows-c4bd73d2-31d7-761e-0178-11268bb10392)

**Comment by FrankBijnen** [comment]
En Anglais maintenant.

Did you have a look at the French translation? And what do you think? As i said I can read French, but I have no idea if the translation is good or not.

Merci Frank

**Comment by FrankBijnen** [comment]
> ✓ TLS 1.2 (https://support.microsoft.com/fr-fr/topic/mise-%C3%A0-jour-pour-activer-tls-1-1-et-tls-1-2-en-tant-que-protocoles-s%C3%A9curis%C3%A9s-par-d%C3%A9faut-dans-winhttp-dans-windows-c4bd73d2-31d7-761e-0178-11268bb10392)

Ah. Tres bien...
