### ISSUE TITLE
Multiple values in reverse geolocation

### ISSUE THREAD

**Issue by apprenti-sorcier** [FrankBijnen/ExifToolGui#359]
In the function “Update City, Province, Country from GPS coordinates”, I would like to select it like this, rather than a single value:
Provice: “state, county”
City: “municipality, town”
and possibly Location: “hamlet, neighbourhood, road”

Now ExifToolGUI only has an option to choose one or none. However these fields are user editable, but when I enter something different than the default options, it doesn’t process it. Am I doing something wrong or could this be a future option?

**Comment by FrankBijnen** [comment]
That's an interesting thought! I will think about it. But this I can say right now:

- When the function "Update City, Province, Country from GPS coordinates” is used with Gecode Provider Exiftool, I have no (or little) control on how the fields are filled. For the other providers it might be possible.
- When you select multiple files (all with the same GPS coordinates preferably) and click on 'Show on Map'. You have the option to click on 'Geotag files'. It will display a form with some values, but these values ARE modifiable!

Note: For the map to work on Windows 7 you may have to install EdgeCanary

![blabla](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/7bbf19a4-6fa7-4c27-8983-17448aef23b4)

**Comment by apprenti-sorcier** [comment]
Thanks for the insight. Indeed, I meant mainly to automatically combine Geocode provider results, but locations could be combined from the Overpass API result.

**Comment by FrankBijnen** [comment]
You could try to write your request on the Exiftool forum https://exiftool.org/forum/
I mean if Exiftool supports it natively, it would very likely be easy to add it to ExifToolGui. Or maybe it would work without having to change anything.

Having said this: I will keep the issue open. I will look into it for a next release.

**Comment by apprenti-sorcier** [comment]
If I understand correctly, the above dialog box doesn’t need access to the Internet mapping to be used. However it’s not active on my computer.

**Comment by FrankBijnen** [comment]
With ExiftoolGui V6.3.0 and ExifTool 12.79 it should be available. (Juist checked the versions, and 12.80 is also available)

And of course it need to be enabled in Preferences.
Option 1 and 3 need 'Enable internet Acces', and 'Enable offline geocoding'
Option 2 only needs 'Enable offline geocoding;

1) 'GeoTag files' from the map
![from the map](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/26a99fe3-d508-41c2-9be4-d833671f9584)

2) 'Modify/Update City etc.' from the file menu.

![modify](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/111123cc-9e0c-4893-abee-28625196e545)
![update](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/5924a1d8-bc06-4be2-a4c7-5d18118dfd2b)

3) It also available to search for a city:

![lyon](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/d482df76-051e-4a00-9243-2c07bd595776)
![lyon2](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e8cfe09f-c6c4-458d-b001-97a7b064ad62)
![lyon3](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/463ae7ee-a656-4174-9a92-850f32845ab5)

Where does it go wrong on your system?

**Comment by apprenti-sorcier** [comment]
I meant the “Geotag files” button.
In my understanding it would allow to edit the address of the photograph. But now I understand it locates the shown map.

**Comment by FrankBijnen** [comment]
Well. I would say it does both. 
- First it gets the Country, Province and City belonging to the coordinates show on top of the map. These coordinates are synced when you move the map.
- Next step, when you press Execute, it fills the values found in the selected files. Note that you can change the values it found in step 1.

Another remark that many users dont read from the docs. When you use CTRL+CLICK, the map is centered according to your mouse position,and the coordinates updated. Added for a better accuracy.

But the question is answered?

**Comment by FrankBijnen** [comment]
@apprenti-sorcier 

Bonjour!

I have made changes to fix this issue. You can download a pre-release here: https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

With this change you can set it up like this:

- Use a * to get all values
- Use a list separated with comma's: e.g.: 6,5,4 or county, state

Frank

Screenshots:

![asterix](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/7218c114-91b0-471e-b944-ee779d17567e)
![list](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/d4cc0dbf-be01-4471-b9ec-5f4c4d07805d)

**Comment by FrankBijnen** [comment]
That error can be caused if you have language dll's from a previous version in the directory where you saved the X64.exe

Things to check:
- Remove the language dll's ExifToolGui_X64.FRA .ENU etc.
- If you want to use the translations, use the installer. First remove the old version completely.

As a side note. Upgrade also to the latest version of ExifTool. (

**Comment by apprenti-sorcier** [comment]
Thank you Frank, this explanation solved the error message.

**Comment by FrankBijnen** [comment]
Thanks for confirming.

If you're interested. See the changelog for what has changed.
https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/changelog.txt

The Docs still need updating!
Frank
