### ISSUE TITLE
Feature Request - Add shortcuts CTRL-C, CTRL-X and CTRL-V to Treeview. Allow copying directories. Improve refreshing 

### ISSUE THREAD

**Issue by emaynard** [FrankBijnen/ExifToolGui#398]
Add the ability to drag and drop file(s) from the Filelist Tab to a different folder location in the Browse pane.  Presumably to mimic the Windows file explorer actions, but my specific need is to Move the file.

Oh... and is there a place to Buy you a Coffee ?

**Comment by FrankBijnen** [comment]
@emaynard 

Hi,

- I never liked drag and drop to move files/folders. To many times I have moved complete folders by mistake and spent lots of time recovering them. (That doesn't mean you can't like it!)
- Besides that, it's not easy to implement. Have a look at https://github.com/andersmelander/Drag-and-Drop-Component-Suite. I would have to add something similar.

Right now you have 2 options to copy/move files.
1) Via shortcuts (Keyboard)
- Select the files you want to copy/move.
- Use Ctrl-C/Ctrl-X to put the filenames on the clipboard
- Navigate to the destination folder.
- In the FileList use CTRL-V

2) Via the Context-Menu (= RightClick in Filelist, or Folder)
- Select the files you want to copy/move.
- In the FileList. RightClick, and choose Copy/Move from the popup menu.
- Rightclick on the destination folder in the Browse pane and choose Paste from the popup menu
or 
- Navigate to the destination folder and RightClick in the filelist, choose Paste from the popup menu

Looking at the code as it is now, I see 2 things that I could improve.
- The Browse pane (Treeview with the folders) does not accept shortcuts (CTRL-C, CTRL-X and CTRL-V). 
- Using CTRL-V does not allow pasting directories.

Would it help you if I added that?

About the coffee. Very friendly of you! But I'm not accepting any money or gifts. Your appreciation is my reward.

Frank

**Comment by FrankBijnen** [comment]
Meanwhile I have taken the liberty to change the description of the feature request, to match the changes made.
