### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by otofoto** [FrankBijnen/ExifToolGui#399]
Option to disable rounding when not using "show values as numbers"

**Comment by FrankBijnen** [comment]
GUI does not round values. If rounding occurs it may be done by Exiftool.

Maybe post your request in the Exiftool.org forum.
Also, please provide some samples.

**Comment by otofoto** [comment]
"show tag values as numbers" disabled
![image](https://github.com/FrankBijnen/ExifToolGui/assets/26463333/a57d86ae-e88c-46e5-928c-a87371e5ff25)

"show values as numbers" enabled
![image](https://github.com/FrankBijnen/ExifToolGui/assets/26463333/7f205c0f-00a3-4364-9401-bd61e9693d3f)

**Comment by FrankBijnen** [comment]
Thanks for the samples.

If you look at https://exiftool.org/faq.html#:~:text=The%20standard%20EXIF%20values%20(EXIF,full%20value%20in%20decimal%20form.)
you can see that that's the way Exiftool works. Gui does nothing to round.

Maybe you can ask the question at the forum?

https://exiftool.org/forum/index.php
