### ISSUE TITLE
Metadata remove XMP-drone-dji

### ISSUE THREAD

**Issue by otofoto** [FrankBijnen/ExifToolGui#400]
Option to add custom XMP group for removal -  "XMP-drone-dji"

**Comment by FrankBijnen** [comment]
There are some many XMP groups, I dont want to add just this one.
Will think of something 'generic'

**Comment by FrankBijnen** [comment]
Hi @otofoto 

I have (finally) made some changes to enable this.
See #418 for more info.

Frank
