### ISSUE TITLE
Sort by filetype not followed by filename sort

### ISSUE THREAD

**Issue by timoto** [FrankBijnen/ExifToolGui#405]
ExifToolGUI V6.3.1.0 x64 Windows Portable
ExifTool V12.84

Expected behaviour: toggle Item Type column will list filetype ascending or descending followed by the filename sorted alphanumerically.

Resulting behaviour: toggle Item Type column will list filetype ascending or descending NOT followed by filename sorting alphanumerically.

A previous version I was using 5.16, does follow the expected behaviour.

**Comment by FrankBijnen** [comment]
The Shellist was created from the ground up. Because the original Shellist was created with a commercial control. So that explains it.

Will look into it, can probably fix it

**Comment by FrankBijnen** [comment]
> Resulting behaviour: toggle Item Type column will list filetype ascending or descending NOT followed by filename sorting alphanumerically.
> 
> A previous version I was using 5.16, does follow the expected behaviour.

I had a look and I dont agree that 5.1.6 sorted on Filename, within FileType. At least not always.
See the screenshot I took of 516. I sorted on FileType. You can see that the 'DNG' is not sorted on Filename

![Sort](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/b24615d4-ed0f-44c9-885b-540320170278)

Having said that, I still think it's a good idea to implement it. I would like to change it, If you like I can give you a download link to a prerel.

Frank
