### ISSUE TITLE
Write GPS coordinates to XMP tags and files

### ISSUE THREAD

**Issue by timoto** [FrankBijnen/ExifToolGui#406]
ExifToolGUI V6.3.1.0 x64 Windows Portable
ExifTool V12.84

Working with, and not wanting to modify original RAW files, we can save meta from Lightroom to XMP files.

We can then modify tags with ExifToolGUI to update the XMP files, but not with GPS data, which is only being written to Exif tags, that don't get updated in XMP files.

How can we set the Geotag files feature to Execute XMP tags for GPS Lat, Lon ?

**Comment by FrankBijnen** [comment]
What I would like is to have the Exiftool command that works.
Gui 'only' executes Exiftool commands

**Comment by FrankBijnen** [comment]
I was away from home when I first read your issue. Reading it again a few times, I think I understand it (better).
Just a few questions to make sure.
Assumptions:
- You have a raw file (CR2, CRW, NEF, DNG etc.) and a XMP Sidecar file.
- You want to geotag that file, but write the Lat,Lon values in the XMP file.
- You dont use the function 'Export/Import' 'Import GPS data from' 'Log files' 
- But you use the 'Geotag files' button, on the MAP.

Questions:
- Do you select the RAW file, or the XMP in the filelist? (I assume the XMP)
- Can you provide a sample XMP?

I still would like to know what ExifTool command GUI should use.

Frank

**Comment by FrankBijnen** [comment]
With the changes applied, XMP files can be processed like image/video files.

**Comment by timoto** [comment]
Hello

It looks like you have updated this feature as I had hoped. Just to confirm:

>     * You have a raw file (CR2, CRW, NEF, DNG etc.) and a XMP Sidecar file.
Yes 
>     * You want to geotag that file, but write the Lat,Lon values in the XMP file.
Yes
>     * You dont use the function 'Export/Import' 'Import GPS data from' 'Log files'
Correct
>     * But you use the 'Geotag files' button, on the MAP.
Yes
 
> Questions:
> 
>     * Do you select the RAW file, or the XMP in the filelist? (I assume the XMP)
XMP

**Comment by timoto** [comment]
> With the changes applied, XMP files can be processed like image/video files.

Is this available to test ?

**Comment by FrankBijnen** [comment]
Yes you can test it: https://github.com/FrankBijnen/ExifToolGui/releases/tag/V6.3.2

**Comment by timoto** [comment]
Yes, seems to work well. Thank you.
