### ISSUE TITLE
copy metadata from file

### ISSUE THREAD

**Issue by otofoto** [FrankBijnen/ExifToolGui#418]
Remember last settings and folder when using copy metadata from file. For example if only GPS tags are needed then it takes time to set it each next photo is chosen.

**Comment by FrankBijnen** [comment]
I'm thinking of redesigning this function, and also remove metadata. I would like to display a 'listview' with all groups actually found in the image. When I start developing that I will add a  'remember last setting'.
Be patient, dont expect anything soon.

**Comment by FrankBijnen** [comment]
Hi @otofoto 

I have made some changes to the removal/import of metadata. The changes in a nutshell:

- The group/tag names are now shown in a listview.
- The items in the listview can be customized. (Add/Del/Edit)
- The last selection is remembered.
- A Button Preview is added, where you can see what tags will be selected for removal/importing.

See screenshots.
One thing I did not change. "Remember last folder setting". I can imagine what you try to achieve with this, and it could be a good idea. But I fear it will confuse most users. As a workaround you could 'pin the folder you need to Quick Access', and select that from the Open Dialog.

The changes will be available in V6.3.5. But if you like to test it, I can send you a 'Pre-release'

Frank

![Remove](https://github.com/user-attachments/assets/5a773334-1930-475a-91fe-7fc98c5d2fec)
![import](https://github.com/user-attachments/assets/fae9afb5-2107-4c6c-afb9-195c9d79117b)
![Quick access](https://github.com/user-attachments/assets/ec327bd6-2d3b-4816-9758-c68655672289)

**Comment by AngusPhoe** [comment]
Hi Frank, I testet the modified "remove metadata" functionality. Looks nice and the possibilities are numberless. In fact, it starts to overlap with some batch files I wrote for delete specific metadata from all my *.JPG and *.MP4. Do you think it would be possible to add deletion configurations? (I know that this can also be done by ExifTool direct)

I don't know if this is a bug or feature: When I delete metadata, the result ´is immediately shown in right metadata section (tab). In the middle filelist section, however, the deleted metadata is still shown in the columns. Only after "Refresh" the metatdat content of the filelist is correct. (In version 6.3.3 I observe the same behaviour)

**Comment by AngusPhoe** [comment]
I tested also the modified import metadata function. Works fine also over various subfolders.

In contrary to the deletion (see previous comment), the new metadata is shown immediately in both the metadata tab as well as within the filelist section.

**Comment by AngusPhoe** [comment]
Can you help me with two questions:

1. If I select "remove ALL metadata" or "import ALL metdata" the listed Tag Names dissappear. Why not leave these Tag Names and make them selected? Is it because more than the listed Tag Names are removed/imported?
2. What does the green plus sign and the red minus sign stand for?

**Comment by FrankBijnen** [comment]
Hi Angus,

Thanks again for testing!


> Do you think it would be possible to add deletion configurations? (I know that this can also be done by ExifTool direct)

Will keep it in mind.

> I don't know if this is a bug or feature: When I delete metadata, the result ´is immediately shown in right metadata section (tab). In the middle filelist section, however, the deleted metadata is still shown in the columns. Only after "Refresh" the metatdat content of the filelist is correct. (In version 6.3.3 I observe the same behaviour)

Will look into it.

>If I select "remove ALL metadata" or "import ALL metdata" the listed Tag Names dissappear. Why not leave these Tag Names and make them selected? Is it because more than the listed Tag Names are removed/imported?

Yes, Possibly more than the listed tag names will be deleted. But I also think it is very clear that ALL will be deleted.

> What does the green plus sign and the red minus sign stand for?

Green plus means: Tag selected for processing
Red Minus means: Tag excluded from processing. A - (minus sign) in front of the tag names triggers this. But the - sign is not very well visible. So I decided to add this to make it stand out.

Note: 
- A Green plus while removing means the tag will be removed, 
- A Green plus while copying means the tag will be copied.

Example usage. Suppose you want to remove all Exif data, except exif:iso and exif:fnumber

![exif_all](https://github.com/user-attachments/assets/542c98c2-d454-4a92-afdd-809631454ff8)

Frank

**Comment by FrankBijnen** [comment]
Hi Angus,

Just to inform you.
Uploaded an updated pre-release that fixes this. 

> I don't know if this is a bug or feature: When I delete metadata, the result ´is immediately shown in right metadata section (tab). In the middle filelist section, however, the deleted metadata is still shown in the columns. Only after "Refresh" the metatdat content of the filelist is correct. (In version 6.3.3 I observe the same behaviour)

Also fixed:
- Some Access Violations that occurred now and then.
- Performance improvements to the sorting.

Frank

**Comment by FrankBijnen** [comment]
Hi Angus

For your information.

> Do you think it would be possible to add deletion configurations? (I know that this can also be done by ExifTool direct)

I added a 'Predefined' button that opens a form where you can define your own configurations. This button is available on 'Remove Metadata', and 'Copy Metadata from ....'. I uploaded a new pre-release version, that contains this change, plus more fixes for Access Violations and sorting.

We are getting close.

Frank
![Predefined](https://github.com/user-attachments/assets/c7d0e7b8-d896-4b19-8606-410ced712436)

**Comment by AngusPhoe** [comment]
> Uploaded an updated pre-release that fixes this.
> 
> > I don't know if this is a bug or feature: When I delete metadata, the result ´is immediately shown in right metadata section (tab). In the middle filelist section, however, the deleted metadata is still shown in the columns. Only after "Refresh" the metatdat content of the filelist is correct. (In version 6.3.3 I observe the same behaviour)

I can confirm the fix.

**Comment by AngusPhoe** [comment]
> I added a 'Predefined' button that opens a form where you can define your own configurations. This button is available on 'Remove Metadata', and 'Copy Metadata from ....'.

I tested both remove and copy. Everything works without errors. 

If you mind, I find one step cumbersome: When being e.g. in the "Remove metadata" window, clicking on the button "Predefined", selecting one key or the coressponding value and pressing the "Ok" button, the list of the tag names are shown in the "Remove metadata" window. I would have however expected, that the single lines of the list are already selected to just continue executing. Or do you have something in mind to let the user select every single tag name? Alternatively, a "select all" field above the single lines could be helpful.

**Comment by FrankBijnen** [comment]
Hi Angus.

Thanks again very much for your efforts. You cant believe how much I appreciate this.

>If you mind,

On the contrary. I like your feedback.

The fact that you mention this is no good news. In my opinion it should be self-explanatory. Obviously it is not, or the function is indeed lousy.
Let me explain how I pictured using it. (Although explaining should not be needed!)

Suppose you want to define 2 extra sets of tags.

XMP, containing the tag XMP:all
Exif_Gps, containing the tags Exif:all and GPS:all

1) remove all tags, with the button Del
2) Use Add, use Free chocice and type in Xmp:all. Click OK
The form should look like this
![1](https://github.com/user-attachments/assets/1951ee7e-e497-4e42-9b9b-49edc872e4d3)

3) Click on Predefined
4) Click on Add, and type in the Key field XMP
![2](https://github.com/user-attachments/assets/34cbd358-f971-40f9-9c5f-25fac8b606d0)
5) Click on OK

6) Do the same for Exif:all and Gps:all
![3](https://github.com/user-attachments/assets/36052533-085b-471b-8d0f-0ac78a551eee)


7) To switch between your configurations, click on Predefined, Select the line and click on OK
![6](https://github.com/user-attachments/assets/4761a421-d0d9-46bf-ae23-120f256e00c2)

8) The list of Tags is now updated.
![7](https://github.com/user-attachments/assets/128e45d3-03db-47ee-bbef-faae317973a4)

9) Switch back
![4](https://github.com/user-attachments/assets/802b4be4-00eb-4b19-aadc-c7ef48e751e1)
![5](https://github.com/user-attachments/assets/10aa9b1d-94b3-4e99-94a9-8ccd72bc1e78)


Obviously we have some kind of misunderstanding, please take the time to explain me. Thanks in advance


Frank

P.S. It looks to me that it was not clear to you that one line in the predefined tags form represents multiple Tags, not just one.

**Comment by FrankBijnen** [comment]
Hi Angus,

Sorry to bother you again. If you dont have time or just dont feel like getting involved let me know, I will not bother you anymore.

I have been thinking about your remarks, and although I dont understand them completely, I felt I had to change the mechanism of changing and selecting the predefined tags. I think it's much cleaner now, both for the user and the program code.

- The buttons 'Add, Delete, Edit' have been deleted from 'Remove and copy metadata' functions.
- A Combobox (Dropdown list) has replaced those,  you can only select 1 from a list of predefined. That will change the tag names accordingly.
![Remove](https://github.com/user-attachments/assets/cbbb474a-740d-4671-b930-9fd2880bae47)

- The Form that opens with the button Predefined now has the options of Adding/Deleting and renaming a predefined list.
- Here you should also Add, Delete, Edit Tag names belonging to the selected predefined list.

 ![predefined](https://github.com/user-attachments/assets/6d17c6e0-24bd-488e-a5cd-0963c292e6c7)

The pre-release has been uploaded. If you would like to have a look I would appreciate it very much.

Frank

**Comment by AngusPhoe** [comment]
Hi Frank,

> If you dont have time or just dont feel like getting involved let me know, I will not bother you anymore.

I am happy if I can be involved. In fact it's the other way around: I am happy that you add new functions - that's the real value adding. 

Right now it might take longer for me to react and answer your posts. It's summertime, so next to work, family and holidays, I don't have so much time to switch on my computer. 

I downloaded the latest prerelease version. The dropdown list is very nice. Everything works fine. 

You explanantions in return to my post [https://github.com/FrankBijnen/ExifToolGui/issues/418#issuecomment-2284810501](https://github.com/FrankBijnen/ExifToolGui/issues/418#issuecomment-2284810501) were already clear to me. I am afraid that I did not express myself clearly enough what I meant. I will try to explain it better by means of screenshots.

Assuming I have defined a set of tags (Angus' tag list) I regularly want to use for mass deletion (or add):

![clip1](https://github.com/user-attachments/assets/f99b1990-55c7-4bcc-bd75-15b741e61977)

After selecting this tag set via the dropdown list I receive the list of predefined tags or tag groups. In the screenshots three lines of tag groups are listed, but not selected:

![clip2](https://github.com/user-attachments/assets/c042b0d2-c9a5-42fb-85d9-7b77565b33d7)

What I would have expected or what I would prefer, respectively, is that the three lines are already selected (because I normally would just like to proceed and finish the deletion):

![clip3](https://github.com/user-attachments/assets/54edcbbf-4d3c-45bc-be4d-8dca9f7762e7)

Alternatively, I thought about a mass selection switch in the list header:

![clip4](https://github.com/user-attachments/assets/f1a84327-c233-4382-88dc-cda9287a453f)

I hope I could make myself clearer. Sorry, if my writing is not always perfect.

Kind regards,

Angus

**Comment by AngusPhoe** [comment]
Btw.: What do you think about placing the "Predefined Tags" window to the preferences, similarly to the Program --> Workspace manager?

**Comment by FrankBijnen** [comment]
> I am happy if I can be involved. In fact it's the other way around: I am happy that you add new functions - that's the real value adding.

Good to know. And should you change your mind in the future. No problem. I understand.
Anyway: Dont let ExifToolGui spoil your holidays!

> I hope I could make myself clearer. Sorry, if my writing is not always perfect.

Yes it's perfectly clear for me now. No excuses needed. I'm Dutch, so my English will not be perfect.

I will certainly think about your proposals.  Let me explain why I chose for the current implementation. 
- In the previous version 'Remove Metadata', and 'Copy metadata into JPG or Tif' always opened without any checks. 
- The Checks you set in the new version are 'remembered'.  So you would only have to set them once. Of course when you keep switching that doesn't help.

> Btw.: What do you think about placing the "Predefined Tags" window to the preferences, similarly to the Program --> Workspace manager?

I could add the Predefined Tags there also. But I also want to keep it where it is now.

Thanks a million,
Frank

**Comment by FrankBijnen** [comment]
Hi Angus,

I couldn't resist making changes rightaway. Hope it makes you happy...

What I did was add checkboxes to the Predefined form also. These checkbox are saved in the ini file of course.
When you select a predefined list, in my screenshot 'Remove FB', GUI will not only copy the tag names from the predefined list, but also the checkmarks. So it is really a one-time job!
![prede](https://github.com/user-attachments/assets/c9294fb2-c8fe-4957-9086-04d1b75649e1)


Should you modify some checkmarks after selecting, then that will be saved and restored. 

Uploaded a new version.

I will do so more testing, bugs are always there! And update the docs.

Please only have a look when you have the time.

Frank

**Comment by AngusPhoe** [comment]
Hi Frank,

I tested the new version of the pre-release. I could not find any bugs. It all works intuitively and fast.

Thanks,

Angus

**Comment by FrankBijnen** [comment]
Hi Angus,

That pleases me. If you feel confident about the new version, please keep using that. Maybe you find something that needs changing.

Thanks,
Frank

**Comment by FrankBijnen** [comment]
Hi Angus,

Just to inform you. I have tried to document the changes:

https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V635.md
See 'Managing metadata' and 'Scanning and displaying sub folders in the filelist'

Also updated the pre-rel. Some smaller things were fixed.

Frank
