### ISSUE TITLE
Map files

### ISSUE THREAD

**Issue by apprenti-sorcier** [FrankBijnen/ExifToolGui#426]
Thanks for the updates.
Where can I find some information about the new feature on Map files. Should I download .map files from OpenStreetMap and provide it to the ExifToolGUI ?

**Comment by FrankBijnen** [comment]
You're Welcome.

Have a look at:
https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/Readme%20GeoCoding.txt

and

https://exiftool.org/geolocation.html (under Alternate Database)

It is NOT related to OpenStreetMap. It has to do with finding places (Cities, Province etc) from coordinates, or finding coordinates from places. If you use Exiftool as geocode provider.

![geocode1](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/acc643e5-eb6d-474d-b4c4-354a7e710da9)
