### ISSUE TITLE
Preview doesn't show correct photo when using up/down keys to select photo/file.

### ISSUE THREAD

**Issue by ralphthecat** [FrankBijnen/ExifToolGui#427]
I am using v 6.3.2.
When I move up and down the filelist using the up and down keys on the keyboard, the preview image doesn't keep up with the file selected.  It seems to be one image/file out of sync.  But if I click on an item in the filelist, the correct preview is shown.

Note that the issue does not occur in the old v5.16 of the program.

I would guess there is a bug in the timing of events related to the handling of up/down keys.

PS - Thanks for resurrecting this program.  I have used it only sporadically, but it is wonderful to have when you need it!

**Comment by FrankBijnen** [comment]
Hi @ralphthecat 

Now that is what I call a bug. I am ashamed.
V6.3.1. Works Ok I think the bug is introduced when fixing https://github.com/FrankBijnen/ExifToolGui/issues/394

Will look into it. Keep you posted.

**Comment by FrankBijnen** [comment]
Luckily it was an easy fix.

Please download the V633 prerel, test it yourself and let me know what you think. https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Frankl

**Comment by ralphthecat** [comment]
That fixed it.  Thanks for the quick response!

**Comment by FrankBijnen** [comment]
And you for testing!
I might release it as V633, because I think it was a really nasty bug. Good that you spotted it.

Frank
