### ISSUE TITLE
Show all files including subfolders

### ISSUE THREAD

**Issue by coolstuff99** [FrankBijnen/ExifToolGui#432]
Hello,

Thanks @FrankBijnen for amazing job continuing with this version of ExifToolGui.
I would like to know if you considered to include option to show all files not only on the selected folder but subfolders as well.
I know can be more resource consuming but ability to handle and see all metadata once will be huge step folder from the original project.

Thank you,

**Comment by FrankBijnen** [comment]
@coolstuff99 

Thanks for your opinion on this version!

The question has been asked before. https://github.com/FrankBijnen/ExifToolGui/issues/246
It would involve a lot of work. The problem is that the ShellTree (Tree of folders) ShellList (List of the Files) are now 'standard' Embarcadero controls, with some additions. These controls only work as they work right now. And it's not easy to modify that.

But I will think about it (again)

Frank

**Comment by coolstuff99** [comment]
Sorry for opening another ticket, I just searched for open ones, not closed...
But I do agree with @AngusPhoe by adding this functionality will be game changer covering all features needed. As he showed, geosetter have this functionality implemented but limited in comparison with exiftoolgui possibilities (no videos and limited file types...)
Thank you for hearing us again :)

**Comment by FrankBijnen** [comment]
@coolstuff99 
@AngusPhoe

Hello,

It's been a long time. But I finally had the time, and insipiration, to look into the subfolder request.
Good news, I think there's a lot of progress. In fact I would like to ask you to test the prerelease 6.3.5. 

This is the download link for the pre-release. https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

The only thing you need to do is edit the file filters. Add ";/s". Upon choosing a file filter with ";/s" added, GUI will scan subfolders for those file types. 
Warning: Choosing subfolders and setting the FileList to 'User Defined' can be time-consuming.
On purpose I'm not revealing anymore, it should be self-explanatory.

Awating your feedback.
Frank 
![filetypes](https://github.com/user-attachments/assets/185b4349-f34d-4711-aa18-5a850bbd7a5d)

**Comment by coolstuff99** [comment]
@FrankBijnen I just got warning from MD and looks like you are trying to solve it https://exiftool.org/forum/index.php?topic=16090.0
till gets fixed I would wait before testing anything. There are plenty of malicious threads nowadays and really hard to trust blinded, sorry.

**Comment by FrankBijnen** [comment]
I understand if you're hesitating. 
The installer V6.3.4 and the prerel V6.3.5 are not considered unsafe by MS defender. You could also use the portable version ExifToolGUI_X64.exe. So I would say it's safe.

But dont do anything that you dont feel confident about.

Frank

**Comment by AngusPhoe** [comment]
Hello Frank,

great to hear from you.

I tested the Version 6.3.5 Pre. 64 Bits. I added "*.jpg;*.mp4;/s" in the file filter. However, I was not able to see the files of the subfolder. Am I doing something wrong?

Kind regards,
Angus

P.S. While testing some (hopefully easy) ideas for improvements in the UI came into my mind. I will share them in another ticket with you.

**Comment by FrankBijnen** [comment]
Maybe you did not check 'Show Folders in filelist'?

(I need to add a note to mention that in the docs!)

![pref](https://github.com/user-attachments/assets/086fd0f9-3ec2-4242-b34f-8bd2d45150a7)

**Comment by FrankBijnen** [comment]
> P.S. While testing some (hopefully easy) ideas for improvements in the UI came into my mind. I will share them in another ticket with you.

So far you've had only good idea's. Looking forward.

Thanks in advance for testing.

Frank

**Comment by AngusPhoe** [comment]
> Maybe you did not check 'Show Folders in filelist'?

Indeed, after checking this option in the preferences I could see the list of files in the subfolders. However, no metadata is shown in the file list window when selecting "User defined". Also, no metadata is shown in the right metadata tab.

![screen](https://github.com/user-attachments/assets/8e448af2-9fe9-4718-a041-dad0784db226)

**Comment by FrankBijnen** [comment]
That's to bad.

You can experiment with the option 'Api WindowsWidefile', to see if that makes a difference.

Can you provide more info?
- I assume the file are all JPG?
- You are running a recent Exiftool?
- I updated the pre-release yesterday. Does that version work maybe?
- Can you share your INI file? So I can test using your settings?

- Can you share the log?
- Open the log window.
- check 'Show all Commands'
- Click on one of the file that give no data.
- I'm especially interested in the Command. At the bottom you see the filename. Is that correct?

Frank

**Comment by AngusPhoe** [comment]
> You can experiment with the option 'Api WindowsWidefile', to see if that makes a difference.

deselecting and selection this option does not make a difference

>     * I assume the file are all JPG?

That's correct.
 
>     * You are running a recent Exiftool?

I used version 12.87. I just downloaded version 12.92 (64 bit) and still could not see metadata in the subfolder files

>     * I updated the pre-release yesterday. Does that version work maybe?

I used the pre-release version that was uploaded yesterday at 09:47:25

>     * Can you share your INI file? So I can test using your settings?

I will send it to you privately.

>     * Can you share the log?
>     * Open the log window.
>     * check 'Show all Commands'
>     * Click on one of the file that give no data.
>     * I'm especially interested in the Command. At the bottom you see the filename. Is that correct?

`-echo4
{ready29}
-CHARSET
FILENAME=UTF8
-CHARSET
UTF8
-v0
-overwrite_original
-sep
*
-m
-P
-c
%.6f°
-API
WindowsWideFile=1
-s3
-f
-Gps:GPSLatitude
-GUI-SEP
-xmp-dc:Subject
-IPTC:Keywords
-XMP-microsoft:LastKeywordIPTC
-XMP-digiKam:TagsList
-XMP-microsoft:LastKeywordXMP
-XMP-lr:HierarchicalSubject
-XMP-iptcExt:PersonInImage
-XMP-acdsee:Categories
-GUI-SEP
-ExifIFD:DateTimeOriginal
-ExifIFD:CreateDate
-IFD0:ModifyDate
-Quicktime:CreateDate
-QuickTime:TrackCreateDate
-QuickTime:MediaCreateDate
-XMP-exif:DateTimeOriginal
-XMP-xmp:CreateDate
-XMP-xmp:ModifyDate
-XMP-xmp:MetadataDate
-XMP-exif:DateTimeDigitized
-FileModifyDate
-ExifIFD:SubSecTime
-ExifIFD:SubSecTimeOriginal
-ExifIFD:SubSecTimeDigitized
-GUI-SEP
-IFD0:Model
-XMP-tiff:Model
-QuickTime:Model
-XMP-tiff:Make
-IFD0:Make
-XMP-xmp:CreatorTool
-XMP-digiKam:ColorLabel
-XMP-exifEX:RecommendedExposureIndex
-XMP-exifEX:SensitivityType
-IFD0:Orientation
-GUI-SEP
-XMP-dc:Description
-XMP-dc:Creator
-XMP-xmp:Rating
-XMP-microsoft:RatingPercent
-XMP-mwg-rs:RegionAreaY
-XMP-mwg-rs:RegionName
-XMP-mwg-rs:RegionType
-ExifIFD:SubjectArea
-IFD0:OtherImage
-:CreationDate
-XMP-MP:RegionPersonDisplayName
-XMP-MP:RegionRectangle
a\3 Resultate
-execute29`

The error is

`Invalid TAG name: ":CreationDate"
Error: File not found - a/3 Resultate`

It seems that the file extension is missing.

**Comment by AngusPhoe** [comment]
I just realized that there is no personal messaging in github. The ini file is also not allowed to attach here. I try it this way:

``
ï»¿[ExifToolGUI]
StartMax=1
BrowseWidth=349
PreviewHeight=348
MetadataWidth=509
MetadataTagWidth=171
DefaultDir=C:\temp
LogWinTop=108
LogWinLeft=109
LogWinWidth=580
LogWinHeight=708
StdColWidth0=200
StdColWidth1=88
StdColWidth2=80
StdColWidth3=120
Def1ColWidth0=64
Def1ColWidth1=64
Def1ColWidth2=48
Def1ColWidth3=73
Def1ColWidth4=73
Def1ColWidth5=56
Def1ColWidth6=88
Def1ColWidth7=80
Def2ColWidth0=120
Def2ColWidth1=48
Def2ColWidth2=80
Def2ColWidth3=80
Def2ColWidth4=120
Def2ColWidth5=120
Def3ColWidth0=120
Def3ColWidth1=48
Def3ColWidth2=120
Def3ColWidth3=120
Def3ColWidth4=120

[GUIsettings]
Language=
AutoRotatePreview=0
FileFilters=*.JPG|*.mp4|*.jpg*|*.jpg;*.mp4;/s
DefStartupUse=0
DefStartupDir=c:\
ETOverrideDir=C:\ProgramPortable\2_Graphik\exiftoolGUI_test\
ETCustomConfig=
ETTimeOut=5000
DefExportUse=0
DefExportDir=
ThumbsSize=0
ThumbAutoGenerate=1
ThumbCleanSet=0000
EnableGMap=1
DefGMapHome=46.55738,15.64608
GUIStyle=Silver
UseExitDetails=0
DetailsSel=4
DetailsDown=1
AutoIncLine=1
DblClickUpdTags=0
ETdirDefCmd=-1
ETdirMode=0
CLFnumber=$00C0DCC0
CLFocal=$00FFDAB6
CLISO=$00D0D0D0
Fast3FileTypes=*.GPX|*.KML
ShowFolders=1
ShowHidden=0
EnableUnsupported=0
ShowBreadCrumb=0
MinimizeToTray=0
SingleInstanceApp=0
ShowBalloon=1
HintHidePause=5000

[EToptions]
DontBackup=1
PreserveDateMod=1
KeySeparator=*
IgnoreErrors=1
GPSinDecimal=1
ShowSorted=1
ShowComposite=0
NotDuplicated=0
APIWindowsWideFile=1
APILargeFileSupport=0
CustomOptions=

[FListUserDefColumn]
Rating=-xmp-xmp:Rating 41
CreateDate=-exif:CreateDate 102
DateTimeOriginal=-exif:DateTimeOriginal 93
ModifyDate=-exif:ModifyDate 103
-exif:Make=-exif:Make 57
-exif:Model=-exif:Model 60
VideoCodec=-QuickTime:CompatibleBrands 25
FileModifyDate=-FileModifyDate 133
Track1MediaCreateDate=-Track1:MediaCreateDate 49
Comment=-XMP-dc:Description 120
Ersteller=-XMP-dc:Creator 96
Subject=-xmp-dc:subject 120

[ETdirectCmd]
Jpg_FileModifyDate_2_ExifDateTimeOriginal=-P "-DateTimeOriginal<FileModifyDate" -overwrite_original_in_place
Jpg_del_mgw-rs=-P -overwrite_original_in_place -XMP-mwg-rs:all=
QuicktimeCreateate_2_AllDates=-P "-Track1:TrackCreateDate<QuickTime:CreateDate" "-QuickTime:MediaCreateDate<QuickTime:CreateDate" "-QuickTime:TrackCreateDate<QuickTime:CreateDate" "-XMP-photoshop:DateCreated<QuickTime:CreateDate" "-XMP-exif:DateTimeOriginal<QuickTime:CreateDate" "-XMP-xmp:CreateDate<QuickTime:CreateDate" "-FileModifyDate<QuickTime:CreateDate" -overwrite_original_in_place

[WorkSpaceTags]
Geotagged?=-Gps:GPSLatitude^
Keywords=-GUI-SEP^
XMP-dc:Subject=-xmp-dc:Subject^[tree] or [flower+rose] or [-fish] or [+bird-fish] ..
Iptc:Keywords=-IPTC:Keywords^No Hint defined
XMP-microsoft:LastKeywordIPTC=-XMP-microsoft:LastKeywordIPTC^No Hint defined
Xmp:Tags List=-XMP-digiKam:TagsList^No Hint defined
XMP-microsoft:LastKeywordXMP=-XMP-microsoft:LastKeywordXMP^No Hint defined
XMP-lr:HierarchicalSubject=-XMP-lr:HierarchicalSubject^No Hint defined
XMP-iptcExt:PersonInImage=-XMP-iptcExt:PersonInImage^No Hint defined
Xmp:Categories=-XMP-acdsee:Categories^No Hint defined
Dates=-GUI-SEP^
Exif:DateTimeOriginal=-ExifIFD:DateTimeOriginal^No Hint defined
Exif:CreateDate=-ExifIFD:CreateDate^No Hint defined
Exif:ModifyDate=-IFD0:ModifyDate^No Hint defined
QuickTime:CreateDate=-Quicktime:CreateDate^No Hint defined
QuickTime:TrackCreateDate=-QuickTime:TrackCreateDate^No Hint defined
QuickTime:MediaCreateDate=-QuickTime:MediaCreateDate^No Hint defined
Xmp:DateTimeOriginal=-XMP-exif:DateTimeOriginal^No Hint defined
Xmp:Create Date=-XMP-xmp:CreateDate^No Hint defined
Xmp:Modify Date=-XMP-xmp:ModifyDate^No Hint defined
Xmp:Metadata Date=-XMP-xmp:MetadataDate^No Hint defined
Xmp:Date/Time Digitised=-XMP-exif:DateTimeDigitized^No Hint defined
FileModifyDate=-FileModifyDate^No Hint defined
Exif:Sub Sec Time=-ExifIFD:SubSecTime^No Hint defined
Exif:Sub Sec Time Original=-ExifIFD:SubSecTimeOriginal^No Hint defined
Exif:Sub Sec Time Digitised=-ExifIFD:SubSecTimeDigitized^No Hint defined
Camera & Photo Settings=-GUI-SEP^
Exif:Camera Model Name=-IFD0:Model^No Hint defined
Xmp:tiff:Model=-XMP-tiff:Model^No Hint defined
QuickTime:Model=-QuickTime:Model^No Hint defined
Xmp:tiff:Make=-XMP-tiff:Make^No Hint defined
Exif:Make=-IFD0:Make^No Hint defined
Xmp:Creator Tool=-XMP-xmp:CreatorTool^No Hint defined
Xmp:Color Label=-XMP-digiKam:ColorLabel^No Hint defined
Xmp:Recommended Exposure Index=-XMP-exifEX:RecommendedExposureIndex^No Hint defined
Xmp:Art der Empfindlichkeit=-XMP-exifEX:SensitivityType^No Hint defined
Exif:Orientation=-IFD0:Orientation^No Hint defined
Various=-GUI-SEP^No Hint defined
XMP-dc:Description=-XMP-dc:Description^No Hint defined
XMP-dc:Creator=-XMP-dc:Creator^No Hint defined
XMP-xmp:Rating=-XMP-xmp:Rating^No Hint defined
XMP-microsoft:RatingPercent=-XMP-microsoft:RatingPercent^No Hint defined
XMP-mwg-rs:RegionAreaY=-XMP-mwg-rs:RegionAreaY^No Hint defined
XMP-mwg-rs:RegionName=-XMP-mwg-rs:RegionName^No Hint defined
XMP-mwg-rs:RegionType=-XMP-mwg-rs:RegionType^No Hint defined
ExifIFD:SubjectArea=-ExifIFD:SubjectArea^No Hint defined
Exif:Other Image=-IFD0:OtherImage^No Hint defined
CreationDate=-:CreationDate^No Hint defined
Xmp:RegionPersonDisplayName=-XMP-MP:RegionPersonDisplayName^No Hint defined
Xmp:RegionRectangle=-XMP-MP:RegionRectangle^No Hint defined

[TagList]
SelCopySingleTags=<
CopySingleTags=Exif:all -Makernotes:All -Gps:All Xmp:All IPTC:All ICC_Profile:All Gps:All<
SelRemoveTags=<
RemoveTags=Exif:All Makernotes:All Gps:All Xmp:All Xmp-exif:All Xmp-Acdsee:All Xmp-Mediapro:All Xmp-Photoshop:All Xmp-crs:All Xmp-Microsoft:All Xmp-pdf:All Xmp-tiff:All Iptc:All Photoshop:All Jfif:All ICC_profile:All<
SelExcludeCopyTags=<
ExcludeCopyTags=exif:ExifImageWidth exif:ExifImageHeight exif:Orientation exif:Xresolution exif:Yresolution exif:ResolutionUnit exif:ColorSpace exif:InteropIndex Makernotes:All Xmp-photoshop:All Xmp-crs:All Xmp-exif:All<
MarkedTags=Artist ImageDescription ProcessingSoftware XPKeywords FileCreateDate DateCreated<
CustomView=-Exif:Artist -ExifToolVersion -ImageDescription -Make -Model -PrintIMVersion -CreateDate -FileModifyDate -FileCreateDate -DateCreated -FileAccessDate -ModifyDate -TrackCreateDate -TrackModifyDate -MediaCreateDate -MediaModifyDate -MetadataDate -Xmp:DateTimeOriginal -Categories -TagsList -PlayMode<

[GeoSettings]
GeoCodeUrl=https://geocode.maps.co
OverPassUrl=https://overpass-api.de/api
GeoLocation500Dir=
GeoCodeApiKey=
GetCoordProvider=0
ThrottleGeoCode=1000
GetPlaceProvider=1
ThrottleOverPass=10
OverPassCaseSensitive=1
OverPassCompleteWord=1
GeoCodeLang=Default
ReverseGeoCodeLang=Default
CountryCodeLocation=1
GeotagMode=1
GeoCodeDialog=0
ReverseGeoCodeDialog=0
GeoCodingEnable=0

[GeoProvince]

[GeoCity]
``

**Comment by FrankBijnen** [comment]
> I just realized that there is no personal messaging in github. The ini file is also not allowed to attach here. I try it this way:

This will work, I will look into it.
If you ever need want to send me a PM in the future: My nickname is FrankB on the ExifTool forum https://exiftool.org/forum/index.php

**Comment by FrankBijnen** [comment]
Hi Angus,

Thanks for your detailed response. I believe that I know what is going on.

if you look at the last part of the command:
> -XMP-MP:RegionRectangle a\3 Resultate -execute29

there is no file extension, as you pointed out. I assume the filename should be 'a\3 Resultate.jpg' ?

Now this is definitely something I need to fix in GUI, so thank you for finding this bug!
But as a workaround you can change this explorer setting. 
**Folder options/Hide extensions for known file types**


![folder options](https://github.com/user-attachments/assets/3c54e2c6-c8db-4dd2-9361-f5eef3816e92)

Two side notes:

> FileFilters=.JPG|.mp4|.jpg|.jpg;.mp4;/s
1) The Filetypes should be defined as \*.jpg;\*.mp4;/s 
In the ini file they are defined without an asterix. Or maybe they got lost when copying into Github?

> CreationDate=-:CreationDate^No Hint defined
2) The Creationdate is not valid

To be continued,

Frank

**Comment by FrankBijnen** [comment]
Hi Angus,

Thanks to your detailed info I was able to fix it. (I hope)
Please download the pre-release again.

Thanks in advance for testing and helping me out,
Frank

**Comment by AngusPhoe** [comment]
> there is no file extension, as you pointed out. I assume the filename should be 'a\3 Resultate.jpg' ?

That's correct.

> But as a workaround you can change this explorer setting. Folder options/Hide extensions for known file types.

That worked ✅ 

> The Filetypes should be defined as *.jpg;*.mp4;/s In the ini file they are defined without an asterix. Or maybe they got lost when copying into Github?

Yes, the asterix got lost during pasting into Github. Next time I will insert it as a code block.

> The Creationdate is not valid

If I add a value to this workspace field and save it, it works. It's saved under XMP-pdf:CreationDate and can also be seen in another application (irfanview)

**Comment by AngusPhoe** [comment]
> Please download the pre-release again.

I downloaded and tested the uopdated prerelease. I could see all files and mass edit metadata without any problems. Sorting and then mass editing also works.
I also tested this behavior after changing the explorer setting (Folder options/Hide extensions for known file types) with positive results.

So, as fas as I used the prerelease, everything worked ✅ 

Thanks again for your great work! 

(P.S. I love and intensively use the shortcuts like Strg+S)

**Comment by FrankBijnen** [comment]
Hi Angus,

Thanks for testing and reporting back. Really enjoyed working with you!
But please keep on using this version. No doubt you will find more issues. Please report any annoyances that you encounter.
I'm still debugging an Access Violation, so the pre-rel is not ready yet! Will inform you when there is news.

BTW: This release also features changes/enhancements when removing and copying metadata. If you have remarks, tips etc, dont hesitate to contact me.

Issues:
https://github.com/FrankBijnen/ExifToolGui/issues/418
https://github.com/FrankBijnen/ExifToolGui/issues/400

For more info see: https://exiftool.org/forum/index.php?topic=16301.0

Frank

**Comment by AngusPhoe** [comment]
I will try to continue testing. However, I will not be able during the next 4 days.

**Comment by FrankBijnen** [comment]
No hurry.

**Comment by FrankBijnen** [comment]
@AngusPhoe 
Hi Angus,

Just released V6.3.5. 
Many thanks for all your help and suggestions!

Frank

**Comment by AngusPhoe** [comment]
Hi Frank, (only came back from holidays yesterday),

I am glad that I could help and give some input to this great tool! 

After another week of holidays (and photos) from tomorrow onwards I look forward to use exiftoolgui for tagging the collected photos of this year so far.

Kind regards,
Angus

P.S. Do you think we can close this issue?

**Comment by FrankBijnen** [comment]
@AngusPhoe 

Hi Angus.
Hope you enjoyed your holiday.

When you notice anything while using GUI dont hesitate to contact me.

Yes, the issue is already closed.

Frank
