### ISSUE TITLE
Getting "Virus detected" when downloading ExifToolGUI installer from Chrome, prevents download

### ISSUE THREAD

**Issue by alelom** [FrankBijnen/ExifToolGui#433]
See:

![image](https://github.com/FrankBijnen/ExifToolGui/assets/6352844/0ac05f42-6521-42fb-a134-5f2359eeb2d5)

This prevents download of the installer.

Chrome Version 125.0.6422.113 (Official Build) (64-bit)
Windows 10

Firefox is instead able to download without issues.

**Comment by FrankBijnen** [comment]
Thanx for the info. 
Alas I'm able to change Chrome. Maybe you can report it to Chrome?

V632 has been downloaded 1500+ times by now, highly unlikely that it contains a virus.

**Comment by alelom** [comment]
Hey, no probs. 

I think the right place to report is the owner's repo because: 
- generally what's needed is some minor modification to the code or repo content to avoid the incorrect flag. In theory, you probably will need to check what's changed in recent chrome versions and comply with their new safety standards. That is, **if** you want to be compliant, which I wouldn't say is a priority unless the issue appears with most other browsers and/or anti-virus services too.
- so users of this repo are aware that this has been raised already and that is a false flag.

**Comment by FrankBijnen** [comment]
I agree that posting here is a good idea.

I dont agree that the installer of GUI should be changed. The installer is created with InnoSetup using this sourcecode;
https://github.com/FrankBijnen/ExifToolGui/blob/main/Redist/ExifToolGUI_install.iss
Lots of installers are created by InnoSettup, and many AV's report false positives. To put it in other words: I wouldn't know what to change.
I think it works best if many people report false positives to Google Chrome.

**Comment by FrankBijnen** [comment]
Meanwhile reported to MS.
![afbeelding](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/084e95f2-6317-49b0-a68b-2139b15f8c41)

**Comment by FrankBijnen** [comment]
@alelom 

Could you please try again?

I updated my definitions, and did not get a virus warning when I tried again. Maybe reporting to MS did help?

**Comment by FrankBijnen** [comment]
@ColmanPerkins-Stephen 

Thanks. 
What can I say? I dont consider it alarming, but that's my opinion.

**Comment by FrankBijnen** [comment]
@PaulCoddington 

Same here.

Downloading with Edge results in: Trojan:Win32/Wacatac.H!ml
Downloading with Chrome results in: Trojan:Win32/QQPass

Previously it was: Trojan:Win32/Vigorf.A

MS cant seem to make up their mind!

**Comment by Philshappy** [comment]
Since the portable version doesn't appear to have this issue would it be possible to continue with the portable version. This tool is so valuable it would be sad not to continue it.

**Comment by FrankBijnen** [comment]
Thanks for your high opinion.

I'm just postponing not abandoning.

It may help if lots of people report this as a false positive to MS.

**Comment by FrankBijnen** [comment]
The installer V633 is no longer reported as a virus.
Just released V634. Just hope that will be fine.
If not then I will report it as a false positive to MS.
