### ISSUE TITLE
How to update File:Comment from a text file

### ISSUE THREAD

**Issue by ahorn-lk** [FrankBijnen/ExifToolGui#437]
Hello all,
I use a tool to "develop" Panasonic RW2 files to JPG format.
Using this tool on JPGs, it removes comments added to it.
I'm now searching **how to** 
 - extract metadata information from a set of JPG files
 - (modify those JPG files with the image editor tool)
 - **recover** the lost **comments (File:Comment) from the exported TXT file.**
I nearly managed to get to this, if I keep a copy of the original JPGs
in a separate directory, then select all modifies JPGs 
and go "Export/Import | Copy Metadata into JPG files)".
![Nearly](https://github.com/FrankBijnen/ExifToolGui/assets/173814051/ddb0884a-b1eb-400a-b402-f32fd009cdce)

Is there a way to make use of the previously exported Metadata in the TXT-file. ?
(probably reducing the long file and filter "File:File name" and "File:Comment" only).

Thanks for your ideas

**Comment by FrankBijnen** [comment]
First of all. You could also post your question in the ExifTool Forum. If you know the ExiFtool command to use, I may be able to tell how that can be done in GUI.

I think your idea is not bad. But I would probably first export to .XMP. Then use the function you mention and use the exported .XMP as input.
Tip: You can create a .PS PowerShell and adapt that to suit your needs.

Note that the function below 'Copy metadata into ALL JPG or TIF files' has a bug. I will fix that. The difference is that that function does not use the selected files, but processes all files in the directory.

See the screenshots.
![export](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/3b8ad25a-47cd-464b-a9d7-6a2b570cea77)
![xmp_created](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/2b734dd6-97ab-4335-aedd-96ebb70ecf2c)
![import1](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e6b5c4ed-b450-47ff-906e-28228fff2877)
![import2](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/30710400-d377-4e0c-9e6d-910546746837)
![import3](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/ee9f649c-db12-4d6e-9946-e0677253fc3e)
![import4](https://github.com/
![powershell](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/9bb9788e-4fcd-4464-81ad-9a60a9b6c4f5)
FrankBijnen/ExifToolGui/assets/63312605/ceb6fa6a-fbb7-406a-a01c-561a7c80b610)

**Comment by FrankBijnen** [comment]
Did some more investigation.

1) File:Comment is not written to .XMP files, or any of the other export formats. So I think you need to save your data to .JPG files.

2) It may be a good option to use 'ExifTool Direct'. Suppose your saved JPG's are saved in a subdir called 'SAVE'. Then you could use this Command:

-TagsFromFile SAVE\\%f.jpg -File:Comment

Tip: Save it as a predefined command.

![ET Direct](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/568f907a-c020-4a6f-9364-800e86e2ff4a)

**Comment by ahorn-lk** [comment]
Hello Frank,

 

thank you for your investigation and replies.

So I was quite close to your recommended steps.

 

Regarding:         “File:Comment is not written to .XMP files”

                            Is that intended or rather a bug ?

and:                    “-TagsFromFile SAVE\%f.jpg -File:Comment” 

                            searches for ALL selected files 

a corresponding (original) file in the SAVE directory

and replaces File:Comment in the related selected file – right?

I will check that right now 😊.

 

Thanks again and best regards

Lutz

**Comment by FrankBijnen** [comment]
> Is that intended or rather a bug ?

First of all. Gui doesn't write tags. It leaves that to ExifTool. So the definitive answer should come from ExifTool. But here's my try:

Generally speaking. Not all tags are applicable to all filetypes. Apparently File:comment is no valid tag to write for XMP.
I know that it is possible to add custom tags to XMP using the ExifTool Config file, but that would be overkill here. I think.

For a complete listing of tagnames per filetype refer to: https://exiftool.org/TagNames/

> and replaces File:Comment in the related selected file – right?

Correct.

**Comment by ahorn-lk** [comment]
Hello Frank,

 

I created a preferred command, made it my default command 
and tested it: It works perfectly and will save me a lot of checking comments and Copy&Paste 😊.



Thank you very much for your help !

Gruß Lutz

**Comment by FrankBijnen** [comment]
You're welcome.
Will close the issue
