### ISSUE TITLE
No executable

### ISSUE THREAD

**Issue by KDMcMullan** [FrankBijnen/ExifToolGui#44]
Thanks for trying to resurrect this.

Please note: https://exiftool.org/forum/index.php?topic=15053.0 says the executable is contained within the Source folder, but I can't see it and I have no way of compiling it.

How weird. Pascal (Turbo Pascal) was the first language I learned at uni, after cutting my teeth on BBC BASIC as a youth.

**Comment by FrankBijnen** [comment]
The executable was initially there, but on request I have created a release. You can find the latest here: https://github.com/FrankBijnen/ExifToolGui/releases/tag/V6.1.0

In the future please check 'Releases'. You can find it on the main page on the right.

Good luck,
Frank
