### ISSUE TITLE
Creating a gpx file

### ISSUE THREAD

**Issue by apprenti-sorcier** [FrankBijnen/ExifToolGui#447]
I would like to create a gpx file from the selected files.
Since there is no command for that, I would use ExifTool direct.

But my command would be as follows:
exiftool -r -if "$gpslatitude" -fileOrder CreateDate -p gpx.fmt {SelectedFiles} > itinéraire.gpx

So my selected files are not at the end of the command line.
Is there a way to create the gpx from ExifToolGUI in this case?

**Comment by FrankBijnen** [comment]
From the Docs, that were taken from Bogdan, there is a note "You can't "redirect" output in ExifTool direct."

https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md#some-examples-for-exercise

If you have a good suggestion how the GUI should be modified, I will consider adding that. And I dont need to know what the executed command should be. That's easy. I would like to know how it should look, how the user should interact. (for example add a button, and show a save dialog etc.)

Having said that, you could use the log window.
- Open the Log window
- Execute the command: "-r -if "$gpslatitude" -fileOrder CreateDate -p gpx.fmt"
- Copy and paste the output into Notepad, or any other editor.
- Dont forget to remove the last line {readyxxx}
- Save it as a GPX

Frank
![log window](https://github.com/user-attachments/assets/38387dbc-62cb-46db-ab65-cf07aa427833)

**Comment by FrankBijnen** [comment]
Assume it can be closed.
