### ISSUE TITLE
Cannot access OSM Maps

### ISSUE THREAD

**Issue by tkrichbaum** [FrankBijnen/ExifToolGui#462]
I used the installer and installed ExiftoolGui_X64.exe of the latest version (6.3.4.0) on Win10.
When I change to the OSM map window, it says that the internet access is not active. (In German: Internetzugang in den Einstellung ist nicht aktiviert). However I can access internet with other programs. What is wrong? 

regards Thomas

![screenshot](https://github.com/user-attachments/assets/e4203981-012e-4ec4-847a-d86b4f1a47fb)

**Comment by FrankBijnen** [comment]
That is easy I think.

Select "Programm/Einstellungen"
Enable "Internetzugang"
![pref](https://github.com/user-attachments/assets/09c99847-619c-4999-8718-b787e54eb073)


I agree that it is a lot to read, but here are the Online Docs: https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md#preferences
