### ISSUE TITLE
ExifToolGUI ability to handle UNC/network path as (startup) parameter

### ISSUE THREAD

**Issue by BorreSanders** [FrankBijnen/ExifToolGui#472]
Hello Frank,

First of all, thanks for picking up on continuing ExifToolGUI development. I recently found out, and like the improvements.
I also found a (for me) typical use-case that does not seem to work due to most of my pictures being on network storage.
I could not find a user forum or your contact data, so I post the issue I bumped into here.
Hope that's OK with you.

Issue:
I'd like to be able to jump right in to some path on the network by passing the network path to the GUI executable as a parameter, formatted as UNC path. With ExifToolGUI (I tried 6.3.4.0, 64bit executable) this does not seem to work.

What works as expected:
C:\Program Files\ExifToolGUI>ExifToolGui_X64.exe "%UserProfile%\pictures"
Result: ExifToolGUI starts up in user picture directory

What doesn't work as expected/hoped for:
C:\Program Files\ExifToolGUI>ExifToolGui_X64.exe "\\\\myServer\home" (UNC path)
Result: ExifToolGUI starts up very slowly and ends up displaying some 'base' screen.

Is this to be a new feature or should this work?

Thanks in advance for your feedback and support!

Kind regards,
Borre Sanders

P.S. I thought this used to work with v5.16, but upon verifying it turned out that actually it already didn't. I used temporary network drive mappings as a workaround.

**Comment by FrankBijnen** [comment]
Hello Borre, (Assume this is your first name)

Thanks for you kind words!

What you describe should work, in the ideal world. I tried to replay your scenario and was surprised by some of the results.

- I'm suspecting the ShellTreeView (on the left) as being the culprit. 
- My first tests make me believe that it is vital that the 'network' node is expandable. It looks like the control is trying to find the pathname in the items, and if that fails it doesn't work.
- Will definitely do some more testing, to see if I can make it work.
- If you can confirm the workarounds, I have something to investigate

Frank

OK:
![network_ok](https://github.com/user-attachments/assets/23d40f5b-5d47-447b-b825-d8c8a0031261)
Not Ok:
![Network_nok](https://github.com/user-attachments/assets/fcf4e437-eefa-4199-92ac-d0b94e011427)

Possible Workarounds:
- Map a drive letter, as you already mentioned.

- Expand the network yourself, manually
-- Startup Exiftoolgui_x64 in a folder on your harddrive.
-- Manually expand the network node and navigate to your UNC path.
-- Now you can drag n drop UNC folders.

- Use the 'Single instance' option, combined with 'When minized moved to tray'.
-- Startup Exiftoolgui_x64 in a folder on your harddrive.
-- Manually expand the network node and navigate to your UNC path.
-- Now you can use 'ExifToolGui_X64 \\\\server\\share\\subfolder'. (Using the single instance will not start a new instance)
-- Dont close GUI, just minimize.

![single](https://github.com/user-attachments/assets/edca0ac0-3d04-46ea-86ec-efe38df7c237)

**Comment by BorreSanders** [comment]
Hello Frank, thanks for your prompt investigation and response! I've found that the network node does not expand, also not on standard File Explorer in Windows (I'm running on Windows 11 Home 23H2). If I (manually) type the UNC path in File Explorer ( e.g. \\\\NAS\home), it does successfully navigate to the network server (NAS) there and displays the folder's contents. Using the single instance option seems to make no difference. Kind regards, Borre

**Comment by FrankBijnen** [comment]
Hello Borre,

Sorry for the confusion about 'single instance'. Let me clarify:

- I figured for your use case 'single instance' would make sense. Else you would end up with a lot of GUI Windows.
- I also discovered that when I was able to expand the network node and navigate to the UNC path manually, from with GUI, and leave that open. Then it would work to start GUI with a UNC path.
- Step by step:
-- Make sure single instance is setup
-- Open Gui in a 'normal harddisk folder'. E.G. in a CMD window ExifToolGui_X64 c:\foto
-- Expand the network node. That can take some time, and possibly give error messages.
-- Navigate to your server, path. If this doesn't work then there's another problem.
-- Dont close GUI.
-- Now try to start GUI in the UNC path. E.G. in a CMD window ExifToolGui_X64 \\server\path
-- The active GUI should respond and open in the \\\\server\\path


But I have more (better) news. I have created a fix. If the path is a UNC path GUI will set the root (Top item) to that path first.
Thereby eliminating the need to expand the network node.
To get back to the desktop click on 'Desktop' in the BreadCrumb bar on top of the filelist.

This is the download link to the V635 pre-rel. Please download, test it, and let me know what you think.
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Frank

**Comment by BorreSanders** [comment]
On my 2 Windows 11 systems network node expansion does not work somehow, neither in File Explorer nor in ExifToolGUI. I'm not sure why, since on the file server WS-Discovery is enabled, and the network is configured to enable netbios on TCP/IP. I'll look into it further some other time. Fixing this is probably most robust, but I have to figure out what's blocking this functionality first.

The preview version with the fix looks somewhat promising, i.e. shows the data in the UNC path. However the navigation structure looks a bit weird, and I could not navigate up and return to the UNC path later if I moved focus to another folder and later decide that I want to return to the view with the UNC path.
![Screenshot 2024-07-28 212017](https://github.com/user-attachments/assets/df8a6934-d591-4cb3-bdde-d4dd52aff267)

**Comment by FrankBijnen** [comment]
Hi Borre,

I'm not convinced that fixing the 'network expansion' will solve all. Expansion works on my W10/W11 systems, and I could reproduce it. But nevertheless it's worth investigating.

Can you indicate what needs to fixed to the pre-rel to make it work for you?

Just a few quick remarks.

>but I have to figure out what's blocking this functionality first.

(Windows) Firewall?

> The preview version with the fix looks somewhat promising

Good to have the confirmation I'm looking at the right spot.

> However the navigation structure looks a bit weird

You mean the 3 triangles? That control replaces a \ with a triangle. I agree it needs fixing, let's focus on getting it working first

>  I could not navigate up and return to the UNC path later.

Suppose you navigated to subfolder(s) of 'home', and want to get back. Just click on 'home'.
Navigating in the Treeview should work.
With the single instance setup, you can just start GUI with the path again.
