### ISSUE TITLE
[Question]: Difference between Options and Preferences

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#490]
Hi Frank,

Is there a reason, why the exiftool specific settings are clustered in the menu "Options", while the remaining settings are clustered under Program->Preferences?

The reason I am asking is, that during our work on the subfolder topic I tried to find some settings. And - because I was not very familiar with most of the settings - I had some troubles to find these settings in the first place. Now, after dealing intesively with the settings, I am familiar with where to find them, but maybe other newbies might struggle like me.

Again, low prio "hygenics" topic. ;-)

Kind regards,

Angus

**Comment by FrankBijnen** [comment]
Hi Angus,

>Is there a reason, why the exiftool specific settings are clustered in the menu "Options", while the remaining settings are clustered under Program->Preferences?

I can only guess, as most of this is done by Bogdan Hrastnik, the initial developer. Whenever I add new options I just add them where I think most people would look for them. 
My assumption is that what is under 'Options' are options for calling Exiftool, while Preferences relate more to how GUI works, Although that is not 100% true.

Example:
'Don't make backup copies' results in '-overwrite_original' 
'Ignore minor errors in metadata' result in '-m'

You can check the options used in the 'Log Window'

In the Preferences menu 
'save Filelist details on exit' make GUI read/write in the INI file.

> I had some troubles to find these settings in the first place. 

All options/preferences are documented in: https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md

Frank

**Comment by AngusPhoe** [comment]
> All options/preferences are documented in: https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md

I must admit, that I never looked at it. Great and detailled documentation!

**Comment by AngusPhoe** [comment]
If okay for you, I will close this issue.

**Comment by FrankBijnen** [comment]
It's OK for me.

The documentation was also initially created by Bogdan. I only updated it to reflect the changes. Credits to him.

Original: https://exiftool.org/gui/

Really appreciate all your input. Thanks.

Frank
