### ISSUE TITLE
Ability to set PATH to exiftool or look in CURRENT directory

### ISSUE THREAD

**Issue by stormy1777** [FrankBijnen/ExifToolGui#505]
I believe prior versions of GUI looked in current directory to pickup exiftool where the newer one does not appear to do that and throws an error at startup:

![image](https://github.com/user-attachments/assets/b3a592ae-fea4-4d6c-a4cb-06fa28e7bdeb)

maybe go a step further and offer a preferences menu to add a lookup directory at startup? with some wrapper script maybe that can easily pickup binary, instead of modifying system/user environment for all sessions?

**Comment by FrankBijnen** [comment]
> I believe prior versions of GUI looked in current directory to pickup exiftool where the newer one does not appear to do that and throws an error at startup:

Gui still searches for ExifTool in the directory where GUI is installed.

> maybe go a step further and offer a preferences menu to add a lookup directory at startup? with some wrapper script maybe that can easily pickup binary, instead of modifying system/user environment for all sessions?

See preferences/other as indicated in the message.
![prefs](https://github.com/user-attachments/assets/ff567f4e-4e28-4882-bc2e-174614daf5c3)

GUI searches for ExifTool.exe in this order:
- The path specified in preferences.
- The directory where GUI was started from
- in the PATH

I would check 3 things if I were you.
- Maybe you navigated in GUI to an invalid folder. 
- Starting with ExifTool 12.88 the instructions have changed. https://exiftool.org/install.html (You need to extract the exiftool_files also)
- Start exiftool from a CMD window and see what happens.

Even easier. Just use the installer. It handles all those things for you.

**Comment by stormy1777** [comment]
Thanks, in my case binary name was called "exiftool(-k).exe" not sure why, certainly I don't recall doing it.. after manually renaming to exiftool.exe, works like a charm.. Thanks @FrankBijnen

**Comment by FrankBijnen** [comment]
Thanks for reporting back. Glad you got it sorted.

If you look at the installation instructions for Windows, point 4, it says to rename the exe after unzipping: https://exiftool.org/install.html

> Even easier. Just use the installer. It handles all those things for you.

![installer](https://github.com/user-attachments/assets/f36e24dc-3616-46a0-b150-a8022dacdfcf)

The whole point of naming the exe "exiftool(-k).exe" is to show 'Press enter" when it has finished processing. So the CMD window remains visible. Typical usage is drag 'n drop from Explorer.

Frank

See screenshots;

![zip](https://github.com/user-attachments/assets/4988feec-43a9-40cc-81bc-db6d177dec18)
![dragdrop](https://github.com/user-attachments/assets/ff6c389f-d2ad-40f9-8463-a1a57f7add18)
![press_enter](https://github.com/user-attachments/assets/69f8cc02-e4c2-466a-9ff2-e3ee6e6800e4)

**Comment by stormy1777** [comment]
thanks, I'msure there is logic and all is documented somewhere, just that defaults might be more in-line with basic usage and not edge-conditions, possibly the binary would ship renamed, and the installer would add the -k to whoever needs it.. 

anyways, that was an easy and fun fix :)
Take care..

    On Saturday, August 17, 2024 at 09:11:49 AM GMT+3, FrankBijnen ***@***.***> wrote:  
 
 


Thanks for reporting back. Glad you got it sorted.

If you look at the installation instructions for Windows, point 4, it says to rename the exe after unzipping: https://exiftool.org/install.html


Even easier. Just use the installer. It handles all those things for you.


installer.jpg (view on web)

The whole point of naming the exe "exiftool(-k).exe" is to show 'Press enter" when it has finished processing. So the CMD window remains visible. Typical usage is drag 'n drop from Explorer.

Frank

See screenshots;

zip.jpg (view on web)
dragdrop.jpg (view on web)
press_enter.jpg (view on web)
