### ISSUE TITLE
Feature request File: Name

### ISSUE THREAD

**Issue by Philshappy** [FrankBijnen/ExifToolGui#546]
Would it be possible to add an option (check box or something) to flip the date with New File Name Starts With and the Change Filename so the renamed filename looks like 'Car 20240606' instead of '20240606 Car'.  I prefer the name first to group or sort by item instead of dates. Also, it appears you cannot select multiple files to be renamed if they have the same dates so would it be possible to add a number in parenthesis starting with a number that is input by the user at the end of the filename.

**Comment by FrankBijnen** [comment]
@Philshappy 

Hi Phil,

Will look into it. Give me some time

Frank

**Comment by FrankBijnen** [comment]
>Would it be possible to add an option (check box or something) to flip the date with New File Name Starts With and the Change Filename so the renamed filename looks like 'Car 20240606' instead of '20240606 Car'. I prefer the name first to group or sort by item instead of dates.

Yes that's possible. Will think of something

>Also, it appears you cannot select multiple files to be renamed if they have the same dates so would it be possible to add a number in parenthesis starting with a number that is input by the user at the end of the filename.

I think you mean that the files will not be unique after renaming. Exiftool has something called \%c that could be used, but I can not find that one can input a nr.

(Look for \%c in https://exiftool.org/exiftool_pod.html)

To be continued,
Frank

**Comment by FrankBijnen** [comment]
Update: I found out how to set a start value, but ExifTool itself seems to have a problem with that.

I'm adding the ExifTool command to use here for future reference.

`exiftool -v0 -overwrite_original "-filename<${Exif:DateTimeOriginal} RenameTest (%%3.4C).%%e" -d %%Y-%%m-%%d File1.jpg `

**Comment by Philshappy** [comment]
Thanks Frank.

When I tried to select multiple images and rename them it was unsuccessful because as you said the file names would not be unique. I think the %c would be OK, creating multiple file names that are not unique.  Say we have 6 images of my cars taken the same day and I want to rename them using only the date no time. Select 3 of them and rename them each with the same dates incorporated. Then try the other 3. Would exiftool create file names for example  '20240303 Car'   20240303 Car -1' and  '20240303 Car -2'  then what would it do when you tried to rename the remaining 3. Would it create '20240303 Car -3' and so on.

Phil
________________________________

**Comment by FrankBijnen** [comment]
Indeed the %c %C is was looking at. Unfortunately the %C (Uppercase) seems to have a problem. (Exiftool will hang sometimes) Need to talk to Phil (Harvey) about that.

Another thought. If I were to use this function for myself I would probably prefer a subdirectory for the 'Cars'.

cars\2024-09-01
cars\2024-09-04

etc. What do you think?

**Comment by Philshappy** [comment]
The subdirectory for each individual function sometimes becomes overwhelming. For example, if I took 20 photos at a car show on 2024-03-03 i would have a lot of subdirectories. In the example below there are 3 images of the same car and that's were the multiple filenames would be useful.
Hopefully ExifTool will be fixed soon so your approach with inserted numbers would be a perfect solution.

Mustang 2024-03-03
Mustang 2024-03-03 -1
Mustang 2024-03-03 -2
Explorer 2024-03-03
Ferrari 2024-03-03
Honda 2024-03-03
And so on.



________________________________

**Comment by FrankBijnen** [comment]
OK. I understand now. Thanks.

Will let you know when I have something ready.

**Comment by FrankBijnen** [comment]
Problem reported to ExifTool:
https://exiftool.org/forum/index.php?topic=16432.0

**Comment by Philshappy** [comment]
Wow that was fast!

Phil
________________________________

**Comment by FrankBijnen** [comment]
Sometimes I am....

Come to think of it. That specific ExifTool command is **only** needed when you want to be able to specify the starting sequence number. If you let ExifTool decide (%C vs %c) then it would work.
Do you rellay need to specify the starting nbr yourself?

Frank

**Comment by Philshappy** [comment]
So it depends on the Exiftool implementation. I noted the situation when you have let's say 6 files. If you use the command on 3 of then I assume Exiftool will add the suffix -1,-2,-3 or something like this.  Now you want to add the 3 remaining. If Exiftool recognizes that -1,-2,and -3 are used and if it then starts with -4 and continues with -5,-6 then I would say you don't need to specify a starting number. I think it would be nice to have the flexibility to specify the starting number but not required.

Phil
________________________________

**Comment by FrankBijnen** [comment]
> If you use the command on 3 of then I assume Exiftool will add the suffix -1,-2,-3 or something like this.  Now you want to add the 3 remaining. If Exiftool recognizes that -1,-2,and -3 are used and if it then starts with -4 and continues with -5,-6 

That is what will happen. But...
Suppose you deleted file -2 before you start renaming the last 3, then the last 3 would be named:
-2, -4 ,-5
In other words: It will fill the gaps.

Another thing: the first file we be named without -1 So in your example:
Cars 20240901.jpg
Cars 20240901-1.jpg
Cars 20240901-2.jpg

second rename
Cars 20240901-3.jpg
Cars 20240901-4.jpg
Cars 20240901-5.jpg

I suggest I start with that option that works (%c), and when Phil Harvey comes with an answer I will look into the other option (%C)

Frank

**Comment by Philshappy** [comment]
Great!  I think it will be a great addition to the rename capability.

Thanks!

Phil
________________________________

**Comment by FrankBijnen** [comment]
Hi Phil,

Made some changes, that you could test.
![Modify_rename](https://github.com/user-attachments/assets/b40e41a0-cc29-447a-bef9-afd4ca289129)

- I have added a CheckBox **-DateTime first**
- And A checkbox **-Unique filenames (%-c)**

The preview should give you an idea. The pre-rel (636) is uploaded to me OneDrive, and also has DateTime shifting updates. See the other issue. 
C:\user\ExifToolGUI\Redist\Prerel\ExifToolGui_PreRel_636.zip

Frank

**Comment by Philshappy** [comment]
Frank,

The rename changes adds a lot of flexibility to changing the file names. Thanks.
      1) When I tried the Remove leading Date/Time it appears to remove whatever is leading so if I renamed the file to 'Car 20240101' instead of removing the date/time it removes the car.
      2) When file names result like 24-01-01-1 is it possible to put a space after the date/time so 24-01-01 -1 or some other delimiter to separate the name from the unique counter.

Comments on the Exif Time Shift
      1) Consider changing the name from Exif DateTime shift to something more descriptive of the full capability as you added file name changes. Maybe 'Date/Time Change'.
      2) The Shift amount and Date Time result to not always track. For example, I edit the date result directly in the text box with 2024:02:02 and the result display the previous date and the following 0078:06:22 00:00:00 shift amount. When I check the increment or decrement the result is a really wrong date.  Similar behavior occurs if I use the down arrow and scroll thru the calendar to select a new date.


Phil

**Comment by Philshappy** [comment]
Accidently closed it.

**Comment by FrankBijnen** [comment]
Thanks for your feedback Phil, really appreciate it.

<      1) When I tried the Remove leading Date/Time it appears to remove whatever is leading so if I renamed the file to 'Car 20240101' instead of removing the date/time it removes the car.
The 2 functions are unrelated. When you click on the bottom button, it **only** removes the part up, and including, the first space found. That's it

Eg. "abcde 12345.jpg" => "12345.jpg"
"12345 abcdef.jpg" => "abcdef.jpg"

>      2) When file names result like 24-01-01-1 is it possible to put a space after the date/time so 24-01-01 -1 or some other delimiter to separate the name from the unique counter.

Will look into it. (maybe 24-01-01 (1).jpg ?)

>      1) Consider changing the name from Exif DateTime shift to something more descriptive of the full capability as you added file name changes. Maybe 'Date/Time Change'.

It still is only shifting. When you have 3 files selected with different dates, the outcome will still be 3 different dates.
2010-01-01 12:00:00
2010-01-02 12:00:00
2010-01-03 12:00:00

When you select the date 2010-02-01 13:00:00 it computes a difference of 1 month and 1 hour 0000:01:00 01:00:00
2010-02-01 13:00:00
2010-02-02 13:00:00
2010-02-03 13:00:00

The intended use was when you have a lot images taken with the camera set to a wrong date/time.
Maybe a new function would be better to avoid confusion. One that sets all selected files to the same date.


>      2) The Shift amount and Date Time result to not always track. For example, I edit the date result directly in the text box with 2024:02:02 and the result display the previous date and the following 0078:06:22 00:00:00 shift amount. When I check the increment or decrement the result is a really wrong date. Similar behavior occurs if I use the down arrow and scroll thru the calendar to select a new date.

Thanks for this. I found 2 problems this morning. Will do some more testing. If I think it's OK, I will inform you.


Frank

**Comment by FrankBijnen** [comment]
Hi Phil,

As promised. I updated the pre-rel. Think it behaves a lot better when you change the date directly. Also I added the date created to the filelist. Makes testing a lot easier.

A few remarks:
- When you move back in time < 1980-01-01 the dates may not show in the filelist.
- When you move even further back < 1600-01-01 the date can not be shown in the calendar.
- And even further back < (around) 1550-01-01 ExifTool will refuse that

Frank
P.S. Only have a look when you have the time....

**Comment by Philshappy** [comment]
Frank,

The enter text box for date/time is much better. A couple of comments.


  1.
For some reason I cannot check the decrement. I can check the increment. When it show no check for the decrement it still decrements.
  2.
Consider the default check box to be empty instead of several being checked. Too many times I found myself changing something cause the box was checked by default.
  3.
The issue I ran into was I wanted the Modify Date and Create Date to be different than the Date Time Original but the shift amount is always computed from the DateTime original. In my particular case the DateTime original, Created Date, and Modified date all were different. How does this happen, well I used a photo editor, which preserves the DateTimeOriginal but modifies the created and modified dates depending on the date you first create the edited photo and then the subsequent dates change the modify. Wow, complex. Its is workable if the Date Created and Date Modified are the same but when they are not the shift time is an issue because it applies the same shift. Consider adding another check box that is shift or absolute and then the calendar can still shift from the Original Date Time but can be applied as either a shift or a value.

Phil
________________________________

**Comment by FrankBijnen** [comment]
Hi Phil,

>  1.
For some reason I cannot check the decrement. I can check the increment. When it show no check for the decrement it still decrements.

When you enter the "shift Amount" you should check "Increment" if you want to move ahead in time. If you want to move back in time, uncheck it. The text will display "decrement" in stead of "Increment". That's how it also worked in previous versions.
When you enter a 'Datetime result" GUI will determine the checkbox for you. If the date is before the current, it will uncheck it, else it will check it.
Does this explanation make sense?

>  2.
Consider the default check box to be empty instead of several being checked. Too many times I found myself changing something cause the box was checked by default.

Which default check box? 
The checkboxes "Original" and "Create"and "change File Create" are checked if GUI finds a valid date time in the file
The checkboxes "Modify" and "change File Modify" are checked if you have enabled "Preserve date modified" in Options
 
If you change nothing and you just press Enter, the date times in the metadata are untouched, and the dates in Explorer reflect the dates in the metadata.

>  3.
The issue I ran into was I wanted the Modify Date and Create Date to be different than the Date Time Original but the shift amount is always computed from the DateTime original. 

Indeed very difficult for me at this time of day after a few beers.
Can you give an example? (Screenshots before/after)

I'm thinking of changing the 'Datetime equalize' so that you can specify all dates. And all selected files will get those dates. Maybe that will solve it?

Frank

(It's 1 after midnight here. I'm going to bed)

**Comment by Philshappy** [comment]
1.
Yes I understood how the check boxes worked but thought it was an error when the decrement doesn't show a check.  Now that you pointed it out I understand.

   2) I was thinking that maximum flexibility was achieved when no check boxes are automatically checked and the user decides which boxes should be checked. For example, the user might want to update the file create date but not the original date, I can see your point as well so its OK.
3) The issue I ran into was I wanted the Modify Date to be different than the Date Time Original and CreateDate but the shift amount is always computed from the DateTime original.  Lets say the Original date and Create Date, are set to 2024-01-01 and the modified date is 2024-01-03. I want the original date and create date to remain 2024-01-01 and the modify date to be 2024-01-05 but when I use the calendar to select the 2024-01-05 it computes the shift from the original date, that would be +4 days but the modified date needs to be +2 days.  Its easy if there is only a couple of days but much harder if its a big difference between them.

Have a good night and get plenty of rest.

Phil

________________________________

**Comment by FrankBijnen** [comment]
Hi Phil,

Again an pre-rel update.  For the rename I have adjusted the layout a little. The Preview has improved, It shows the filename you type in now.
![rename1](https://github.com/user-attachments/assets/faf72a08-186f-4377-a19b-4660bc6414c3)

See the other issue (545) for what has changed to the date time shifting.

Frank

**Comment by FrankBijnen** [comment]
Hi Phil,

Phil Harvey has fixed the bug I found when using the rename with %2.4C in ExifTool 12.97.
https://exiftool.org/forum/index.php?topic=16432.0

When I have the time I will update the rename function accordingly, So you can specify the starting sequence number. 
Will keep you posted.

Frank

**Comment by FrankBijnen** [comment]
@Philshappy 

Hi Phil,
I finally had the time to update the rename function. It looks like this now:

If you choose 'Use standard sequence' (=Default) renaming works like in the previous version:
![Rename standard](https://github.com/user-attachments/assets/e450bc9c-f4eb-4da2-8c9c-f07da3bf5cf6)

If you choose 'Use custom sequence' you can change the format of the sequence number.
- You can add characters before and after. Default `-( `and `)` 
- You can change the starting number. Default 0
- You can change the positions to use for the number (1-5)
![Rename custom](https://github.com/user-attachments/assets/9148bd5e-fb46-446e-9a33-9d2e55429e13)

**You need at least ExifTool Version 12.97 to use this!**

The download link is still the same: https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Note: The version 6.3.6 also includes this change: https://github.com/FrankBijnen/ExifToolGui/issues/484
In the ZIP file you will find a PDF that gives more info.

Frank

**Comment by Philshappy** [comment]
Frank,

Wow so many great changes. The implementation for the file renaming is awesome. I really like how you implemented the numbering options when there are multiple files. Also, the new file list implementation is really nice. I really like you how you integrated the option of adding multiple file list column views instead of having to load each one via the user load. I was wondering if there was a way to copy these user custom file list views to multiple machines. In the past i copied the configuration settings files for each file list view and for each workspace and put them in the same folder as the application and used the load feature to select them. I would consider having a single configuration file for all computers but each of my computers has a different folder structure and configuration, making the preferences an issue.  Can I copy just the following from the main configuration settings and past it into another computer's main configuration file.

[UsrColDef_0]
ReadMode=2
FileType=-File:FileType 72,0;0
DateTimeOriginal=-*:DateTimeOriginal 154,0;0
OffsetTime=-*:OffsetTime 91,0;0
TimeZone=-*:TimeZone 80,0;0
TimeZoneOffset=-*:TimeZoneOffset 122,0;0
OffsetTimeOriginal=-*:OffsetTimeOriginal 146,0;0
FileModifyDate=-System:FileModifyDate 189,0;0


In the future, consider modifying the user workspace customization just like you did the file lists custom column views.

Thanks so much for the great work.

Phil
________________________________

**Comment by FrankBijnen** [comment]
Hi Phil,

Thanks for your compliments! (If I would be younger, it would make me blush)

> Can I copy just the following from the main configuration settings and past it into another computer's main configuration file.

Yes, You can do that, but you would also need the copy this:
[UserDefLists]
0=User Defined

And if you had defined multiple user defined list, you would also find
1 = xxx 
2 = xxx

This function is intended for transfering your settings. it will create an ini file with all your file list definitions. That ini file you can import on an other computer. (Importing will overwrite all file list definitions)

![im_export](https://github.com/user-attachments/assets/7087ba2a-2876-4c4a-ab3a-eeec5dff1bdb)

> In the future, consider modifying the user workspace customization just like you did the file lists custom column views.

Will keep it in mind, but I make no promises.

Frank

Could be a few weeks, before I release V636. Need to update the docs.

**Comment by FrankBijnen** [comment]
Hi Phil,

Here I am again...

Just to inform you. Because of issue #616 I had to modify the 'Rename' function. It is now possible to also use XMP date fields. The preview has also improved a bit.

![rename](https://github.com/user-attachments/assets/06e8639c-81b4-436a-b323-ea664c91cb30)

In case you want to have a look and test if it still works as expected, here's the download link: https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Frank

**Comment by Philshappy** [comment]
Frank,

Works great.

Thanks,

Phil
________________________________

**Comment by FrankBijnen** [comment]
Hi Phil,

The release V636 is nearly ready. Just going through the docs, and awaiting an ExifTool fix. This is the 'release info', as you can see I'm mentioning you. Unless you prefer not to?

Anyway, thanks again for your input and testing!

Frank

![relnfo](https://github.com/user-attachments/assets/5afa4e97-d751-436d-a4d0-bd84d299187b)

**Comment by Philshappy** [comment]
Thanks so much for the great work. Looking forward to its release.

Phil

________________________________
