### ISSUE TITLE
Ensure selected item in Filelist Listview is visible in Directory Treeview 

### ISSUE THREAD

**Issue by FrankBijnen** [FrankBijnen/ExifToolGui#558]

**Comment by FrankBijnen** [comment]
@angusphoe

Hi Angus,

I think this is what you mean. 

- When you have /s Subfolders enabled.
- You can scroll in the filelist so far down, that the subfolder is not 'in view' in the treeview on the left.
- The change created for this issue scrolls the treeview, so that the subfolder will be visible, when you select a file on the right.
- I can not select it in code, because that would mean refreshing the filelist.
- In the screenshot 2018-10-05 is not visible on the left, selecting any of the files on the right (2018-10-05) will scroll the treeview on the left.
- A side-effect is, that if the directory name on the left is to large to fit, it will also scroll horizontal.

I must admit that I'm not that pleased with how it works, and if I keep it like this I will make a parameter in preferences that defaults to false.

Frank
P.S.: I cant tell you how glad I am with this kind of feedback!

![sample](https://github.com/user-attachments/assets/2bd2377e-3f01-4b13-b942-8a79b8a0a48b)

**Comment by AngusPhoe** [comment]
Hi Frank, 

yes, I believe your explanation is what I meant. I did not even had many subfolders, but the effect is the same. I attach a screencast, which explains more than thousend words. 

The whole issue is not really high priority. I commented to this behaviour, because exiftoolgui did not behave like this before.


https://github.com/user-attachments/assets/aa4e9603-1ed6-4910-aafe-b61f4b7cef4b

**Comment by AngusPhoe** [comment]
> I cant tell you how glad I am with this kind of feedback!

And I am very glad that you are so open to my feedbacks. Great collaboration.

**Comment by FrankBijnen** [comment]
Angus,

As I see it I have a few options.

- Leave it like it is
- Remove the code
- Only do this when a new option (Sync Treeview) in Preferences is checked

I can even see if I manage to prevent the horizontal scrolling. But that might not be possible.

What do you prefer?

Frank

**Comment by AngusPhoe** [comment]
(Will not be able to respond for the next 4 days)

**Comment by FrankBijnen** [comment]
Ok. Thanks. 
Whatever it is you will do, have fun.

**Comment by FrankBijnen** [comment]
FYI

>Leave it like it is. It does not annoy anybody I assume.

I did, but modified it a little. The treeview is now only synced when it is actually needed, and the horizontal scrollbar is unchanged. How it was meant to be!

**Comment by AngusPhoe** [comment]
> FYI
> 
> > Leave it like it is. It does not annoy anybody I assume.
> 
> I did, but modified it a little. The treeview is now only synced when it is actually needed, and the horizontal scrollbar is unchanged. How it was meant to be!

Sounds good. Thanks.
