### ISSUE TITLE
Writing GPS coordinates to image

### ISSUE THREAD

**Issue by JCFLux1** [FrankBijnen/ExifToolGui#560]
Hello Frank
I like to add GPS data to an image that is taken without the camera writing GPS data to the image. I'm tracking the location in several .gpx files which I'm matching to the image via timestamp. I'm facing the following issues:
When selecting "Import GPS data from log file" -> "-use all log files in directory", I'm getting the following error message:

No matching file found for -geotag option

Out of the ExifTool LOG:
Executed command:
-echo4
{ready25}
-CHARSET
FILENAME=UTF8
-CHARSET
UTF8
-v2
-overwrite_original
-sep
*
-P
-c
%.6f°
-API
WindowsWideFile=1
-API
GeoDir=C:\Program Files\ExifToolGUI\GeoLocation500
-geotag
C:\Users\xxxx\Documents\Tracks*.gpx
-geotime<${DateTimeOriginal}+09:00
-API
GeoMaxExtSecs=1800
image.JPG
-execute25

Output:
{ready25}

If I'm not selecting "-use all log files in directory", I'm getting the following executed command:

-echo4
{ready27}
-CHARSET
FILENAME=UTF8
-CHARSET
UTF8
-v2
-overwrite_original
-sep
*
-P
-c
%.6f°
-API
WindowsWideFile=1
-API
GeoDir=C:\Program Files\ExifToolGUI\GeoLocation500
-geotag
C:\Users\xxxx\Documents\Tracks\activity_17020580474.gpx
-geotime<${DateTimeOriginal}+09:00
-API
GeoMaxExtSecs=1800
image.JPG
-execute27

with the following error message: Warning: No writable tags set from image.JPG.

Output:
Loaded 377 points from XML-format GPS track log file 'C:\Users\Jxxxx\Documents\Tracks\activity_17020580474.gpx'
  GPS track start: 2024:09:11 05:29:42.000 UTC
  GPS track end:   2024:09:11 06:31:52.000 UTC
Writing File:Geotag
======== image.JPG
Setting new values from image.JPG
  Geotime value:   2024:09:11 02:49:41.000 UTC
Nothing changed in image.JPG
    0 image files updated
    1 image files unchanged
{ready27}

It only works if I have an image file where the GPS Tag names are already created and the tool is then only updating the values and if I'm selecting one .gpx file at the time e.g. not ticking "-use all log files in directory".

-echo4
{ready36}
-CHARSET
FILENAME=UTF8
-CHARSET
UTF8
-v2
-overwrite_original
-sep
*
-P
-c
%.6f°
-API
WindowsWideFile=1
-API
GeoDir=C:\Program Files\ExifToolGUI\GeoLocation500
-geotag
C:\Users\Jean-Claude\Documents\xxxx\Tracks\activity_16909041039.gpx
-geotime<${DateTimeOriginal}+09:00
-API
GeoMaxExtSecs=1800
image1.JPG
-execute36

Output:
Loaded 269 points from XML-format GPS track log file 'C:\Users\xxxx\Tracks\activity_16909041039.gpx'
  GPS track start: 2024:08:31 05:41:36.000 UTC
  GPS track end:   2024:08:31 06:18:37.000 UTC
Writing File:Geotag
======== image1.JPG
Setting new values from image1.JPG
  Geotime value:   2024:08:31 05:43:53.000 UTC
Writing Keys:GPSCoordinates if tag exists
Writing UserData:GPSCoordinates if tag exists
Writing UserData:GPSCoordinates if tag exists
Writing ItemList:GPSCoordinates
Writing MIE-GPS:GPSLatitude
Writing XMP-drone-dji:GPSLatitude if tag exists
Writing XMP-exif:GPSLatitude if tag exists
Writing GPS:GPSLatitude
Writing MIE-GPS:GPSLongitude
Writing XMP-drone-dji:GPSLongitude if tag exists
Writing XMP-exif:GPSLongitude if tag exists
Writing GPS:GPSLongitude
Writing MIE-GPS:GPSAltitude
Writing XMP-exif:GPSAltitude if tag exists
Writing GPS:GPSAltitude
Writing XMP-exif:GPSAltitudeRef if tag exists
Writing GPS:GPSAltitudeRef
Writing Reconyx:AmbientTemperature if tag exists
Writing Reconyx:AmbientTemperature if tag exists
Writing Reconyx:AmbientTemperature if tag exists
Writing Sony:AmbientTemperature if tag exists
Writing XMP-exifEX:AmbientTemperature if tag exists
Writing ExifIFD:AmbientTemperature
Writing GPS:GPSLatitudeRef
Writing GPS:GPSLongitudeRef
Writing GPS:GPSDateStamp
Writing GPS:GPSTimeStamp
Writing XMP-exif:GPSDateTime if tag exists
Rewriting image1.JPG...
  Editing tags in: APP0 APP1 CIFF ExifIFD File GPS IFD0 ItemList JFIF Keys MIE-GPS MakerNotes UserData XMP 
  Creating tags in: APP1 ExifIFD File GPS IFD0 ItemList MIE-GPS 
JPEG APP1 (32142 bytes)
  Rewriting IFD0
  Rewriting ExifIFD
  Rewriting MakerNoteNikon
  Rewriting VRInfo
  Rewriting PictureControlData
  Rewriting WorldTime
  Rewriting ISOInfo
  Rewriting DistortInfo
  Rewriting UnknownInfo
  Rewriting HDRInfo
  Rewriting ShotInfoD850
  Rewriting MenuSettingsOffset
  Rewriting MoreSettingsOffset
  Rewriting CustomSettingsOffset
  Rewriting OrientationOffset
  Rewriting ColorBalanceUnknown2
  Rewriting LensData0204
  Rewriting FlashInfo0107
  Rewriting MultiExposure
  Rewriting AFInfo2
  Rewriting FileInfo
  Rewriting AFTune
  Rewriting RetouchInfo
    - ExifIFD:AmbientTemperature = '31'
    + ExifIFD:AmbientTemperature = '31'
  Rewriting InteropIFD
  Rewriting GPS
    - GPS:GPSLatitudeRef = 'N'
    + GPS:GPSLatitudeRef = 'N'
    - GPS:GPSLatitude = '35 27 3.998049052'
    + GPS:GPSLatitude = '35 27 3.99804907351207'
    - GPS:GPSLongitudeRef = 'E'
    + GPS:GPSLongitudeRef = 'E'
    - GPS:GPSLongitude = '139 38 53.65509259'
    + GPS:GPSLongitude = '139 38 53.6550925213716'
    - GPS:GPSAltitudeRef = '0'
    + GPS:GPSAltitudeRef = '0'
    - GPS:GPSAltitude = '32.67692185'
    + GPS:GPSAltitude = '32.6769218444824'
    - GPS:GPSTimeStamp = '5 43 53'
    + GPS:GPSTimeStamp = '05 43 53'
    - GPS:GPSDateStamp = '2024:08:31'
    + GPS:GPSDateStamp = '2024:08:31'
  Rewriting IFD1
JPEG APP1 (13308 bytes)
  Rewriting XMP
    [XMP rewritten with no changes]
JPEG APP2 (4092 bytes)
JPEG DQT (130 bytes)
JPEG SOF0:
JPEG DHT (416 bytes)
JPEG SOS
    1 image files updated
{ready36}

BTW, when trying around I was using the ExifToolGui v5.xx to add the GPS values to another test images. The "-use all log files in directory" parameter worked as expected and also the creation of the Tag names and values was working fine.

I assume that I'm missing a parameter to tell the v6.xx tool that the GPS Tag names need to get created when not existing and to use all files in the folder for the GPS data import.

Using version 6.3.5.0 64 Bits of ExifToolGui

I'm not an expect, so I hope you can help me here.

Many Thx

**Comment by FrankBijnen** [comment]
@JCFLux1 

Hello,

I read 2 things in this issue.

1) "use all log files in directory" does not work as expected. I had a quick look at the code and found a bug that I introduced. I will fix it for the next release, but that will be a while. If you want this sooner, let me know.
2) You get an error "No Writeable tags set". If you look at the **bold** lines in the log you see that the geotime ExifTool computes from the image is not within the range of the GPX file. You can adjust the default margin of 1800 and try again. Or maybe you need another log file.

Frank

Output:
Loaded 377 points from XML-format GPS track log file 'C:\Users\Jxxxx\Documents\Tracks\activity_17020580474.gpx'
**GPS track start: 2024:0911 05:29:42.000 UTC
GPS track end: 2024:09:11 06:31:52.000 UTC**
Writing File:Geotag
======== image.JPG
Setting new values from image.JPG
**Geotime value: 2024:09:11 02:49:41.000 UTC**
Nothing changed in image.JPG
0 image files updated
1 image files unchanged

**Comment by JCFLux1** [comment]
Hello

Thanks for the fast feedback
Regarding 1:
OK for me to wait for the next release, I use as a workaround in the meanwhile the separate selection of each .gpx file.
Regarding 2:
Based on your comments I have redone a run. All fine now. Point closed for me, Thx

JCF

**Comment by FrankBijnen** [comment]
Hello JCF,

Thanks for your feedback.

Regarding 1:
I have created an issue for this: https://github.com/FrankBijnen/ExifToolGui/issues/561  

Frank

**Comment by FrankBijnen** [comment]
Hello JCF,

I have created a fix version V6.3.5.1. You can download it from here:

https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

The zip only contains the Exe and Map files, no installer, that would require some more work.

Please check that the fix works, if you have the time. 

Thanks,
Frank

**Comment by JCFLux1** [comment]
Hi Frank

Working as expected
Many Thx

JCF
