### ISSUE TITLE
bloodhound.w32.ep

### ISSUE THREAD

**Issue by Ract0** [FrankBijnen/ExifToolGui#576]
Hi.
Today, when installing ExifToolGUI_install_6.3.5.0, Norton 360 informed me of this virus in the language packs: exiftoolgui_x64.NLD, ITA, FRA, ESP, ENU, DEU, CHS.
It’s probably a false positive since I haven’t seen other reports, but I would still like to confirm it.
Thanks.

**Comment by FrankBijnen** [comment]
Hi,

Thanks for informing me. 
Yes, very likely a false positive. These language files dont contain executable code.
If you are willing to help, please report this to Norton 360 as being a false positive. I can't, I'm not a customer.

Frank

(Will leave thise issue open for a while)

**Comment by macg12** [comment]
Problem with Norton 360 but different virus flag
Nortons 360
ExifGUI_install_6.3.5.0.exe
High risk
Threat name: FileRepMalware [Misc]
Quarantined

Is it clean?

**Comment by FrankBijnen** [comment]
I thought I had replied, but it doesnt show here. So here again.

Yes, it is clean. But please upload a sample to your antivirus supplier.

Frank

**Comment by macg12** [comment]
Thanks Frank. All done. All good ;-)

**Comment by FrankBijnen** [comment]
Thanks for confirming. I'll close the issue.

The past year I have released a version every 6-10 weeks. So it will likely not be the last time.
