### ISSUE TITLE
Cannot shift .xmp time

### ISSUE THREAD

**Issue by szotsaki** [FrankBijnen/ExifToolGui#616]
I'd like to increase the created timestamp with 56 minutes for all .xmp files (coming from Lightroom). I selected all the files, set the dialogue this way, and pressed Execute:

![image](https://github.com/user-attachments/assets/a307092c-8295-4da9-b705-35bb93b0d694)

During execution, I get one warning for each file:
```
Warning: No writable tags set from _MG_0001.xmp
Warning: No writable tags set from _MG_0004.xmp
[...]
```

In the logs I see:
```
    0 image files updated
   42 image files unchanged
```

Command line:
```
-echo4
{ready41}
-CHARSET
FILENAME=UTF8
-CHARSET
UTF8
-v0
-overwrite_original
-sep
*
-c
%.6f°
-API
WindowsWideFile=1
-API
LargeFileSupport=1
-API
GeoDir=C:\[...]\AppData\Local\Programs\ExifToolGUI\GeoLocation500
-FileModifyDate<Exif:DateTimeOriginal
_MG_0001.xmp
_MG_0004.xmp
[...]
-execute41
```

Some additional notes:
- I find it a bit strange that the first three fields (which contain a hyphen) are read-only. If it's intended, they should be text fields in my opinion.
- The meaning of the asterisks (before DateTime) is also unclear. If they mean compulsory fields why the text box is read only?
- It's also not apparent for me what does "minus shift" mean with a checkbox.

**Comment by FrankBijnen** [comment]
Hi szotsaki,

This function works on EXIF dates, not on XMP dates. Image files, like JPG or camera raw, have EXIF dates, and possibly XMP dates. 
XMP files dont have EXIF dates. 

If you execute this command: -G -s -alldates in ExifTool Direct with the log window open, you will see something like this:

```
======== _IGP0001.dng
[EXIF]          DateTimeOriginal                : 2024:10:10 14:59:35
[EXIF]          CreateDate                      : 2024:10:10 14:59:35
[EXIF]          ModifyDate                      : 2024:10:10 17:24:16
======== _IGP0001.xmp
[XMP]           CreateDate                      : 2024:10:10 14:59:35
[XMP]           ModifyDate                      : 2024:10:10 17:24:16+02:00
    2 image files read
```
The -G shows you in which group the tags are. (EXIF, XMP)


>    I find it a bit strange that the first three fields (which contain a hyphen) are read-only. If it's intended, they should be text fields in my opinion.

They contain the hyphen, because there is no data.

>    The meaning of the asterisks (before DateTime) is also unclear. If they mean compulsory fields why the text box is read only?

>    It's also not apparent for me what does "minus shift" mean with a checkbox.

Good observations. Honoustly I can only guess, they were added by the previous developer Bogdan Hrastnik.

The asterixes may mean that they are related. So if you shift 1 hour, the DateTime result shown is 1 hour later/sooner as the DateTime original. 
The Hyphens I have no idea. 

To shift your XMP dates you can use ExifTool direct.
Advance 1 hour
 `-Alldates+="0:0:0 1:0:0"`

Back 1 day:
 `-Alldates-="0:0:1 0:0:0"`

Or set the date time 
 `-Alldates="2024:10:11 12:00:00"`

![xmp](https://github.com/user-attachments/assets/95fe50aa-6a2d-4a25-8db9-f41a3029f42f)

Frank

**Comment by szotsaki** [comment]
Thank you for the `Alldates` examples, they were very useful and solved the problem at hand.

The XMP I saved from Lightroom has DateTimeOriginal field (but this is a new save coming from retesting):
```
[XMP]           DateTimeOriginal                : 2024:01:14 10:35:20.87+01:00
[XMP]           CreateDate                      : 2024:01:14 10:35:20.87+01:00
[XMP]           ModifyDate                      : 2024:01:14 10:35:20.87+01:00
```

![image](https://github.com/user-attachments/assets/9e9218c4-25b5-483b-b91f-74a57f2861f8)

I don't know what the green highlight means, though.

I can see this is more likely an exiftool issue rather than the GUI frontend problem.

The dialogue simplification (or making it more obvious) would be nice but I let it for you to close this bug or keep it open.

**Comment by FrankBijnen** [comment]
> I don't know what the green highlight means, though.

You can add fields to the Workspace for editing. (Right click, Add tag to Workspace) Fields already added to the Workspace are green.
https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md#pop-up-menu-in-metadata-panel

> I can see this is more likely an exiftool issue rather than the GUI frontend problem.

Well I wouldn't say it's an exiftool issue. Exiftool distinguishes groups and tags. And tags can be in multiple groups. This reminds me. You should add `-a` to the command I gave you `-G -s -alldates` or Exiftool will only display the first tag ( `-G -s -a -alldates` ).

> The dialogue simplification (or making it more obvious) would be nice but I let it for you to close this bug or keep it open.

- The previous developer has used a lot of times hyphens where bullets would be more appropriate. Have a look at 'Program/Preferences' ,or the online documentation.  I dont want to change that. 
- The asterixes I can get rid of.
- I will think of a way to make the function work for dates not in the EXIF group. 
- Will leave this issue open.

For the next release V6.3.6, that will be released in a couple of weeks, I have already made changes to this function. It now looks like this:
![shift](https://github.com/user-attachments/assets/af43c200-8796-44fc-985e-a69112bbdbf2)


Thanks!

Frank
