### ISSUE TITLE
Charts X axes are not naturally ordered

### ISSUE THREAD

**Issue by szotsaki** [FrankBijnen/ExifToolGui#619]
Go to chart and select FLength or FNumber. Their X axes ordering is 1..10..11..2..20..3, etc.

![image](https://github.com/user-attachments/assets/634ab48f-f49a-4392-8ed2-decffbd138a5)

Please, change them to follow natural ordering.

Another note that probably the graph should omit missing values. This way the ISO values should be a lot better represented without a lot of 0-valued bars and the FLength and FNumber wouldn't need to have a cap on them. I'm sure there are people who have longer lenses than 300 mm :).

**Comment by FrankBijnen** [comment]
Hi szotsaki,

> Please, change them to follow natural ordering.

I have fixed the sorting on my development version. It wasn't properly handling decimal values!
The fix will be in V6.3.6. I dont know yet when that will be released.

> Another note that probably the graph should omit missing values. This way the ISO values should be a lot better represented without a lot of 0-valued bars 

The program is excluding files that have NO VALUE. (See Whatsappxxxxx_No_ISO.jpg) It does not exclude '0' values. (See Whatsappxxxx_ISO_0.jpg)
I think it's a good idea to exclude those values from the chart. That's another fix for V6.3.6.
**Can you confirm that only value '0' should be excluded?**

How to check with Exiftool Direct:
`-n -f -filename -ISO -FNUMBER -FOCALLENGTH`
```
======== WhatsApp Image 2024-01-15 at 13.30.35_76948233_Values_0.jpg
File Name                       : WhatsApp Image 2024-01-15 at 13.30.35_76948233_Values_0.jpg
ISO                             : 0
F Number                        : 0
Focal Length                    : 0
======== WhatsApp Image 2024-01-15 at 13.30.35_76948233_No_Values.jpg
File Name                       : WhatsApp Image 2024-01-15 at 13.30.35_76948233_No_Values.jpg
ISO                             : -
FNUMBER                         : -
FOCALLENGTH                     : -
    2 image files read
```
> and the FLength and FNumber wouldn't need to have a cap on them. I'm sure there are people who have longer lenses than 300 mm :).

The program does not cap, it shows all values. The labels are only meant to give you an idea of the possible data. 
**What would be sensible values in the labels?**

![flength](https://github.com/user-attachments/assets/6f50d16b-a774-4c2a-9421-412a51a98567)

Frank
P.S.: I really like this kind of feedback.
