### ISSUE TITLE
[bug] If file name starts with a whitespace or "-" no metada is displayed

### ISSUE THREAD

**Issue by Box333** [FrankBijnen/ExifToolGui#668]
the title sais it all.
i have a file "- ABC8639.JPG".
 no metada is displayed
when i rename it to  "ABC8639.JPG" metada is displayed

**Comment by FrankBijnen** [comment]
I looked into it, and was able to reproduce. Hope to create a permanent fix for the next version V6.3.6. but will need info from Phil Harvey.
Will keep you posted.

Meanwhile you could try to uncheck 'Options/Api WindowswWideFile', that should work.
Frank
