### ISSUE TITLE
[bug?] no thumbnails shown for videos encoded with av1

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#711]
Hello Frank,

I recently switched the encoder for all my videos from x265 to av1. While I could see thumbnails for videos encoded with x265 in the preview window, I only see a four colored thumbnail for videos encoded with av1 now, see attachment.

Do you know, what the reason is?

The encoding is done by using ffmpeg: `%path_ffmpeg% -y -i in.mp4 -pix_fmt yuv420p10le -c:v libsvtav1 -crf 45 -preset 8 -g 240 -svtav1-params tune=0:enable-variance-boost=1 -acodec libmp3lame -q:a 7 -map_metadata 0 out.mp4`
![screenshot](https://github.com/user-attachments/assets/694d474b-edfe-46e0-921a-544ea16da843)

**Comment by FrankBijnen** [comment]
Hi Angus,

For the preview panel (Left-Bottom) Gui first tries to get the thumbnail from WIC. (Windows Imaging Component) This works for Images. (JPG, Tiff, PNG and raw files) 
For an MP4 this will (likely) not work, and GUI falls back to the standard Windows Thumbnail.

https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellitemimagefactory-getimage

So my question is: Does Windows Explorer show thumbnails?

Frank

**Comment by AngusPhoe** [comment]
Hi Frank, thanks for the quick response and the explanation, how thumbnails are generated.

Windows Explorer (which I never use) does not show the thumbnails of av1 videos, either.

I found a solution via your posted links. I installed Icaros (https://github.com/Xanashi/Icaros), and everythink works like a charm.

Thanks again for your help.

Angus

**Comment by FrankBijnen** [comment]
Very good Angus,

Thanks for confirming my assumption. I have starred the Icaros repository in case I get a similar question.
Always a pleasure communicating with you!

Frank
